
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface BusinessUnit
{
    static public final int ADMIN_SRVS = 0;
    static public final int AGRIFOODS = 1;
    static public final int AIR_FORCE = 2;
    static public final int ARMY = 3;
    static public final int AUTOMOTIVE = 4;
    static public final int BUSINESS_OFFICE_OPERATIONS = 5;
    static public final int COMMUNICATIONS = 6;
    static public final int CORE_TECH = 7;
    static public final int DOE = 9;
    static public final int D_D = 8;
    static public final int ENERGY_PRODUCTS = 10;
    static public final int ENVIRONMENTAL = 11;
    static public final int ES_H = 12;
    static public final int FACILITIES = 13;
    static public final int FINANCE = 14;
    static public final int HEALTHCARE_PRODUCTS = 16;
    static public final int HEALTH_AND_HUMAN_SRVS = 15;
    static public final int HUMAN_RESOURCES = 17;
    static public final int INFORMATION_MANAGEMENT = 18;
    static public final int INTEGRATED_PRODUCT_DEVELOPMENT = 19;
    static public final int LEGAL = 20;
    static public final int NASA = 21;
    static public final int NAVY = 23;
    static public final int NSD = 22;
    static public final int OCEO = 24;
    static public final int ORGANIZATIONAL_DEVELOPMENT = 25;
    static public final int OTHER = 28;
    static public final int SPECIAL_PROGRAMS = 26;
    static public final int TRANSPORTATION = 27;
}
