
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface Division
{
    static public final int COMMERCIAL_MARKET_SECTOR = 1;
    static public final int CORPORATE = 3;
    static public final int GOVERNMENT_MARKET_SECTOR = 0;
    static public final int PACIFIC_NORTHWEST_NATIONAL_LABORATORY = 2;
}
