
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface JobFunction
{
    static public final int COMPLIANCE__AUDIT__AND_ACCOUNTING = 11;
    static public final int DISTRIBUTION = 13;
    static public final int ENVIRONMENTAL__HEALTH__AND_SAFETY = 1;
    static public final int FACILITIES_MANAGEMENT = 6;
    static public final int HUMAN_RESOURCES = 2;
    static public final int INFORMATION_TECHNOLOGY = 3;
    static public final int LEGAL_AND_REGULATORY = 4;
    static public final int MANUFACTURING = 7;
    static public final int MARKETING__PR_AND_COMMUNICATIONS = 5;
    static public final int OTHER = 14;
    static public final int RESEARCH_AND_DEVELOPMENT = 8;
    static public final int SALES = 12;
    static public final int STRATEGY = 9;
    static public final int TREASURY__INVESTMENT__AND_RISK_MANAGEMENT = 10;
}
