
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface JobLocation
{
    static public final int ABERDEEN__MD = 0;
    static public final int ANNISTON__AL = 1;
    static public final int ATLANTA__GA = 2;
    static public final int CLEVELAND__OH = 3;
    static public final int COLUMBUS__OH = 4;
    static public final int CRYSTAL_CITY__VA = 5;
    static public final int DAYTON__OH = 6;
    static public final int DUXBURY__MA = 7;
    static public final int EDGEWOOD__MD = 8;
    static public final int HAMPTON__VA = 9;
    static public final int MELBORNE__FL = 10;
    static public final int RICHLAND__WA = 11;
    static public final int SAN_ANTONIO__TX = 12;
    static public final int SEATTLE__WA = 13;
    static public final int SPARTA__NJ = 14;
    static public final int WARNER_ROBINS__GA = 15;
    static public final int WASHINGTON__DC = 16;
}
