
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface JobTitle
{
    static public final int EXECUTIVE = 5;
    static public final int LINE_MANAGEMENT = 2;
    static public final int MIDDLE_MANAGEMENT = 3;
    static public final int SENIOR_MANAGEMENT = 4;
    static public final int SUBJECT_MATTER_EXPERT = 1;
}
