
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface LookupResultType
{
    static public final int ABBREVIATION = 2;
    static public final int CAPTION = 1;
    static public final int ID = 0;
}
