
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface RiskRating
{
    static public final int HIGH__7_ = 7;
    static public final int HIGH__8_ = 8;
    static public final int HIGH__9_ = 9;
    static public final int LOW__1_ = 1;
    static public final int LOW__2_ = 2;
    static public final int LOW__3_ = 3;
    static public final int MEDIUM__4_ = 4;
    static public final int MEDIUM__5_ = 5;
    static public final int MEDIUM__6_ = 6;
    static public final int UNKNOWN = 0;
}
