
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db;

public interface Enum
{
    static public final int BOOK_TYPE = 3;
    static public final int LOOKUP_RESULT_TYPE = 0;
    static public final int RECORD_STATUS = 1;
}
