
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db;

public interface Table
{
    static public final int ASSET = 2;
    static public final int ASSET_LOAN = 4;
    static public final int BORROWER = 3;
}
