
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db;

public interface Table
{
    static public final int BOOK_INFO = 2;
}
