
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db;

public interface Table
{
    static public final int ACCOUNT = 3;
    static public final int BANNER_DATA = 4;
    static public final int CATEGORY = 5;
    static public final int ITEM = 7;
    static public final int LINEITEM = 11;
    static public final int ORDERSTATUS = 10;
    static public final int ORDERS = 9;
    static public final int PRODUCT = 6;
    static public final int PROFILE = 2;
    static public final int SUPPLIER = 8;
}
