
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form;

public interface Library
{
    static public final String BOOK_INFO = "library.book-info";
}
