
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface Language
{
    static public final int ENGLISH = 0;
    static public final int FRENCH = 1;
    static public final int JAPANESE = 2;
    static public final int URDU = 3;
}
