
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.coordinator;

public interface CompleteProfile
{
    static public final String DATE_OF_BIRTH = "date_of_birth";
    static public final String EMAIL = "email";
    static public final String ETHNICITY_ID = "ethnicity_id";
    static public final String GENDER_ID = "gender_id";
    static public final String HOME_PHONE = "home_phone";
    static public final String LANGUAGE_ID = "language_id";
    static public final String NAME_FIRST = "name_first";
    static public final String NAME_LAST = "name_last";
    static public final String NAME_MIDDLE = "name_middle";
    static public final String NAME_PREFIX = "name_prefix";
    static public final String NAME_SUFFIX = "name_suffix";
    static public final String PASSWORD1 = "password1";
    static public final String PASSWORD2 = "password2";
    static public final String SSN = "ssn";
    static public final String USER_ID = "user_id";
    static public final String WORK_PHONE = "work_phone";
}
