
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.org;

public interface Employee
{
    static public final String DATE_OF_BIRTH = "date_of_birth";
    static public final String EMAIL = "email";
    static public final String EMPLOYEE_NUMBER = "employee_number";
    static public final String GENDER_ID = "gender_id";
    static public final String JOB_TITLE = "job_title";
    static public final String MARITAL_STATUS_ID = "marital_status_id";
    static public final String NAME_FIRST = "name_first";
    static public final String NAME_LAST = "name_last";
    static public final String NAME_MIDDLE = "name_middle";
    static public final String NAME_SUFFIX = "name_suffix";
    static public final String ORG_ID = "org_id";
    static public final String PHONE = "phone";
    static public final String SSN = "ssn";
}
