
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.org;

public interface PersonRegistration
{
    static public final String CR_ORG_ID = "cr_org_id";
    static public final String CR_PERSON_ID = "cr_person_id";
    static public final String ORG_ID = "org_id";
    static public final String ORG_NAME = "org_name";
    static public final String REL_PERSON_ID = "rel_person_id";
}
