
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.org;

public interface Profile
{
    static public final String BILLING = "billing";
    static public final String CITYSTATEZIP = "cityStateZip";
    static public final String COUNTRY = "country";
    static public final String EMAIL = "email";
    static public final String EMPLOYEES = "employees";
    static public final String LINE1 = "line1";
    static public final String LINE2 = "line2";
    static public final String ORG_ABBREV = "org_abbrev";
    static public final String ORG_CODE = "org_code";
    static public final String ORG_ID = "org_id";
    static public final String ORG_NAME = "org_name";
    static public final String ORG_TYPE_ID = "org_type_id";
    static public final String PRIMARY = "primary";
    static public final String TIME_ZONE = "time_zone";
    static public final String WEBSITE = "website";
}
