
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.person;

public interface Notes
{
    static public final String ID = "ID";
    static public final String DATE = "date";
    static public final String NOTES = "notes";
}
