
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface AssetType
{
    static public final int BOOK = 3;
    static public final int OTHER = 0;
    static public final int PERIODICAL = 2;
    static public final int SOFTWARE = 1;
}
