
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface BookType
{
    static public final int BUSINESS = 2;
    static public final int CHEMISTRY = 5;
    static public final int INFORMATION_TECHNOLOGY = 3;
    static public final int MYSTERY = 1;
    static public final int NUCLEAR_PHYSICS = 4;
    static public final int SCIENCE_FICTION = 0;
}
