
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface LoanType
{
    static public final int LONG_TERM = 1;
    static public final int SHORT_TERM = 0;
}
