
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form;

public interface Coordinator
{
    static public final String COMPLETE_PROFILE = "coordinator.complete-profile";
    static public final String SHORT_PROFILE = "coordinator.short-profile";
}
