
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form;

public interface Cts
{
    static public final String PERSON_CONTACT_INFO = "cts.person-contact-info";
}
