
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form;

public interface Org
{
    static public final String ADDRESS = "org.address";
    static public final String EMPLOYEE = "org.employee";
}
