
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form;

public interface Org
{
    static public final String PERSON_REGISTRATION = "org.person_registration";
    static public final String PROFILE = "org.profile";
}
