
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form;

public interface Person
{
    static public final String CONTACT_INFO = "person.contact-info";
    static public final String CONTACT_METHOD = "person.contact_method";
    static public final String NOTES = "person.notes";
    static public final String SELF_LOGIN_INFO = "person.self-login-info";
}
