
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form;

public interface Sponsor
{
    static public final String ADDRESS = "sponsor.address";
    static public final String COMPLETE_INFO = "sponsor.complete-info";
    static public final String CONTACT_INFO = "sponsor.contact-info";
    static public final String SHORT_INFO = "sponsor.short-info";
}
