
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form;

public interface Study
{
    static public final String NEW_SPONSOR = "study.new-sponsor";
    static public final String PROFILE = "study.profile";
}
