
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form;

public interface Subject
{
    static public final String COMPLETE_PROFILE = "subject.complete-profile";
    static public final String LOGIN_INFO = "subject.login_info";
    static public final String PROFILE = "subject.profile";
    static public final String SHORT_PROFILE = "subject.short-profile";
}
