
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.survey;

public interface Additional
{
    static public final String RISK_GROUP_ADDITIONAL_1 = "risk_group_additional_1";
    static public final String RISK_GROUP_ADDITIONAL_2 = "risk_group_additional_2";
    static public final String RISK_GROUP_ADDITIONAL_3 = "risk_group_additional_3";
    static public final String RISK_NAME_ADDITIONAL_1 = "risk_name_additional_1";
    static public final String RISK_NAME_ADDITIONAL_2 = "risk_name_additional_2";
    static public final String RISK_NAME_ADDITIONAL_3 = "risk_name_additional_3";
    static public final String RISK_RESPONSE_ADDITIONAL_1 = "risk_response_additional_1";
    static public final String RISK_RESPONSE_ADDITIONAL_2 = "risk_response_additional_2";
    static public final String RISK_RESPONSE_ADDITIONAL_3 = "risk_response_additional_3";
    static public final String RISK_ROW_SYSTEM_ID_ADDITIONAL_1 = "risk_row_system_id_additional_1";
    static public final String RISK_ROW_SYSTEM_ID_ADDITIONAL_2 = "risk_row_system_id_additional_2";
    static public final String RISK_ROW_SYSTEM_ID_ADDITIONAL_3 = "risk_row_system_id_additional_3";
}
