
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.survey;

public interface External
{
    static public final String RISK_GROUP_NATURAL_HAZARD = "risk_group_natural_hazard";
    static public final String RISK_GROUP_POLITICAL = "risk_group_political";
    static public final String RISK_GROUP_REGULATORY = "risk_group_regulatory";
    static public final String RISK_GROUP_TECHNOLOGY = "risk_group_technology";
    static public final String RISK_NAME_NATURAL_HAZARD = "risk_name_natural_hazard";
    static public final String RISK_NAME_POLITICAL = "risk_name_political";
    static public final String RISK_NAME_REGULATORY = "risk_name_regulatory";
    static public final String RISK_NAME_TECHNOLOGY = "risk_name_technology";
    static public final String RISK_RESPONSE_NATURAL_HAZARD = "risk_response_natural_hazard";
    static public final String RISK_RESPONSE_POLITICAL = "risk_response_political";
    static public final String RISK_RESPONSE_REGULATORY = "risk_response_regulatory";
    static public final String RISK_RESPONSE_TECHNOLOGY = "risk_response_technology";
    static public final String RISK_ROW_SYSTEM_ID_NATURAL_HAZARD = "risk_row_system_id_natural_hazard";
    static public final String RISK_ROW_SYSTEM_ID_POLITICAL = "risk_row_system_id_political";
    static public final String RISK_ROW_SYSTEM_ID_REGULATORY = "risk_row_system_id_regulatory";
    static public final String RISK_ROW_SYSTEM_ID_TECHNOLOGY = "risk_row_system_id_technology";
}
