
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.survey;

public interface InternalFinancial
{
    static public final String RISK_GROUP_COUNTER_PARTY = "risk_group_counter_party";
    static public final String RISK_GROUP_LIQUIDITY = "risk_group_liquidity";
    static public final String RISK_NAME_COUNTER_PARTY = "risk_name_counter_party";
    static public final String RISK_NAME_LIQUIDITY = "risk_name_liquidity";
    static public final String RISK_RESPONSE_COUNTER_PARTY = "risk_response_counter_party";
    static public final String RISK_RESPONSE_LIQUIDITY = "risk_response_liquidity";
    static public final String RISK_ROW_SYSTEM_ID_COUNTER_PARTY = "risk_row_system_id_counter_party";
    static public final String RISK_ROW_SYSTEM_ID_LIQUIDITY = "risk_row_system_id_liquidity";
}
