
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.survey;

public interface InternalOperationalBusinessReporting
{
    static public final String RISK_GROUP_BUDGETING_PLANNING = "risk_group_budgeting_planning";
    static public final String RISK_GROUP_INVESTMENT = "risk_group_investment";
    static public final String RISK_GROUP_MGMT_REPORTING = "risk_group_mgmt_reporting";
    static public final String RISK_GROUP_REGULATORY = "risk_group_regulatory";
    static public final String RISK_GROUP_STRATEGIC_PLANNING = "risk_group_strategic_planning";
    static public final String RISK_NAME_BUDGETING_PLANNING = "risk_name_budgeting_planning";
    static public final String RISK_NAME_INVESTMENT = "risk_name_investment";
    static public final String RISK_NAME_MGMT_REPORTING = "risk_name_mgmt_reporting";
    static public final String RISK_NAME_REGULATORY = "risk_name_regulatory";
    static public final String RISK_NAME_STRATEGIC_PLANNING = "risk_name_strategic_planning";
    static public final String RISK_RESPONSE_BUDGETING_PLANNING = "risk_response_budgeting_planning";
    static public final String RISK_RESPONSE_INVESTMENT = "risk_response_investment";
    static public final String RISK_RESPONSE_MGMT_REPORTING = "risk_response_mgmt_reporting";
    static public final String RISK_RESPONSE_REGULATORY = "risk_response_regulatory";
    static public final String RISK_RESPONSE_STRATEGIC_PLANNING = "risk_response_strategic_planning";
    static public final String RISK_ROW_SYSTEM_ID_BUDGETING_PLANNING = "risk_row_system_id_budgeting_planning";
    static public final String RISK_ROW_SYSTEM_ID_INVESTMENT = "risk_row_system_id_investment";
    static public final String RISK_ROW_SYSTEM_ID_MGMT_REPORTING = "risk_row_system_id_mgmt_reporting";
    static public final String RISK_ROW_SYSTEM_ID_REGULATORY = "risk_row_system_id_regulatory";
    static public final String RISK_ROW_SYSTEM_ID_STRATEGIC_PLANNING = "risk_row_system_id_strategic_planning";
}
