
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.survey;

public interface InternalStrategic
{
    static public final String RISK_GROUP_BUSINESS_MODEL = "risk_group_business_model";
    static public final String RISK_GROUP_BUSINESS_PORTFOLIO = "risk_group_business_portfolio";
    static public final String RISK_GROUP_INTELLECUAL_PROPERTY = "risk_group_intellecual_property";
    static public final String RISK_GROUP_MARKETING = "risk_group_marketing";
    static public final String RISK_NAME_BUSINESS_MODEL = "risk_name_business_model";
    static public final String RISK_NAME_BUSINESS_PORTFOLIO = "risk_name_business_portfolio";
    static public final String RISK_NAME_INTELLECUAL_PROPERTY = "risk_name_intellecual_property";
    static public final String RISK_NAME_MARKETING = "risk_name_marketing";
    static public final String RISK_RESPONSE_BUSINESS_MODEL = "risk_response_business_model";
    static public final String RISK_RESPONSE_BUSINESS_PORTFOLIO = "risk_response_business_portfolio";
    static public final String RISK_RESPONSE_INTELLECUAL_PROPERTY = "risk_response_intellecual_property";
    static public final String RISK_RESPONSE_MARKETING = "risk_response_marketing";
    static public final String RISK_ROW_SYSTEM_ID_BUSINESS_MODEL = "risk_row_system_id_business_model";
    static public final String RISK_ROW_SYSTEM_ID_BUSINESS_PORTFOLIO = "risk_row_system_id_business_portfolio";
    static public final String RISK_ROW_SYSTEM_ID_INTELLECUAL_PROPERTY = "risk_row_system_id_intellecual_property";
    static public final String RISK_ROW_SYSTEM_ID_MARKETING = "risk_row_system_id_marketing";
}
