
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.survey;

public interface InternalOperationalHumanCapital
{
    static public final String RISK_GROUP_AUTHORITY_LIMIT = "risk_group_authority_limit";
    static public final String RISK_GROUP_COMMUNICATIONS = "risk_group_communications";
    static public final String RISK_GROUP_PERSONNEL = "risk_group_personnel";
    static public final String RISK_GROUP_PLACEMENT = "risk_group_placement";
    static public final String RISK_GROUP_TRAINING = "risk_group_training";
    static public final String RISK_NAME_AUTHORITY_LIMIT = "risk_name_authority_limit";
    static public final String RISK_NAME_COMMUNICATIONS = "risk_name_communications";
    static public final String RISK_NAME_PERSONNEL = "risk_name_personnel";
    static public final String RISK_NAME_PLACEMENT = "risk_name_placement";
    static public final String RISK_NAME_TRAINING = "risk_name_training";
    static public final String RISK_RESPONSE_AUTHORITY_LIMIT = "risk_response_authority_limit";
    static public final String RISK_RESPONSE_COMMUNICATIONS = "risk_response_communications";
    static public final String RISK_RESPONSE_PERSONNEL = "risk_response_personnel";
    static public final String RISK_RESPONSE_PLACEMENT = "risk_response_placement";
    static public final String RISK_RESPONSE_TRAINING = "risk_response_training";
    static public final String RISK_ROW_SYSTEM_ID_AUTHORITY_LIMIT = "risk_row_system_id_authority_limit";
    static public final String RISK_ROW_SYSTEM_ID_COMMUNICATIONS = "risk_row_system_id_communications";
    static public final String RISK_ROW_SYSTEM_ID_PERSONNEL = "risk_row_system_id_personnel";
    static public final String RISK_ROW_SYSTEM_ID_PLACEMENT = "risk_row_system_id_placement";
    static public final String RISK_ROW_SYSTEM_ID_TRAINING = "risk_row_system_id_training";
}
