
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.survey;

public interface InternalOperationalTechnology
{
    static public final String RISK_GROUP_ACCESS = "risk_group_access";
    static public final String RISK_GROUP_AVAILABILITY = "risk_group_availability";
    static public final String RISK_GROUP_INFRASTRUCTURE = "risk_group_infrastructure";
    static public final String RISK_NAME_ACCESS = "risk_name_access";
    static public final String RISK_NAME_AVAILABILITY = "risk_name_availability";
    static public final String RISK_NAME_INFRASTRUCTURE = "risk_name_infrastructure";
    static public final String RISK_RESPONSE_ACCESS = "risk_response_access";
    static public final String RISK_RESPONSE_AVAILABILITY = "risk_response_availability";
    static public final String RISK_RESPONSE_INFRASTRUCTURE = "risk_response_infrastructure";
    static public final String RISK_ROW_SYSTEM_ID_ACCESS = "risk_row_system_id_access";
    static public final String RISK_ROW_SYSTEM_ID_AVAILABILITY = "risk_row_system_id_availability";
    static public final String RISK_ROW_SYSTEM_ID_INFRASTRUCTURE = "risk_row_system_id_infrastructure";
}
