
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.survey;

public interface InternalOperationalProcess
{
    static public final String RISK_GROUP_CONTRACT = "risk_group_contract";
    static public final String RISK_GROUP_ENVIRONMENTAL = "risk_group_environmental";
    static public final String RISK_GROUP_HEALTH_AND_SAFETY = "risk_group_health_and_safety";
    static public final String RISK_GROUP_PRODUCT_SERVICE = "risk_group_product_service";
    static public final String RISK_GROUP_PROJECT = "risk_group_project";
    static public final String RISK_GROUP_RELATIONSHIP_MANAGEMENT = "risk_group_relationship_management";
    static public final String RISK_GROUP_SECURITY = "risk_group_security";
    static public final String RISK_GROUP_THIRD_PARTY_LIABILITY = "risk_group_third_party_liability";
    static public final String RISK_NAME_CONTRACT = "risk_name_contract";
    static public final String RISK_NAME_ENVIRONMENTAL = "risk_name_environmental";
    static public final String RISK_NAME_HEALTH_AND_SAFETY = "risk_name_health_and_safety";
    static public final String RISK_NAME_PRODUCT_SERVICE = "risk_name_product_service";
    static public final String RISK_NAME_PROJECT = "risk_name_project";
    static public final String RISK_NAME_RELATIONSHIP_MANAGEMENT = "risk_name_relationship_management";
    static public final String RISK_NAME_SECURITY = "risk_name_security";
    static public final String RISK_NAME_THIRD_PARTY_LIABILITY = "risk_name_third_party_liability";
    static public final String RISK_RESPONSE_CONTRACT = "risk_response_contract";
    static public final String RISK_RESPONSE_ENVIRONMENTAL = "risk_response_environmental";
    static public final String RISK_RESPONSE_HEALTH_AND_SAFETY = "risk_response_health_and_safety";
    static public final String RISK_RESPONSE_PRODUCT_SERVICE = "risk_response_product_service";
    static public final String RISK_RESPONSE_PROJECT = "risk_response_project";
    static public final String RISK_RESPONSE_RELATIONSHIP_MANAGEMENT = "risk_response_relationship_management";
    static public final String RISK_RESPONSE_SECURITY = "risk_response_security";
    static public final String RISK_RESPONSE_THIRD_PARTY_LIABILITY = "risk_response_third_party_liability";
    static public final String RISK_ROW_SYSTEM_ID_CONTRACT = "risk_row_system_id_contract";
    static public final String RISK_ROW_SYSTEM_ID_ENVIRONMENTAL = "risk_row_system_id_environmental";
    static public final String RISK_ROW_SYSTEM_ID_HEALTH_AND_SAFETY = "risk_row_system_id_health_and_safety";
    static public final String RISK_ROW_SYSTEM_ID_PRODUCT_SERVICE = "risk_row_system_id_product_service";
    static public final String RISK_ROW_SYSTEM_ID_PROJECT = "risk_row_system_id_project";
    static public final String RISK_ROW_SYSTEM_ID_RELATIONSHIP_MANAGEMENT = "risk_row_system_id_relationship_management";
    static public final String RISK_ROW_SYSTEM_ID_SECURITY = "risk_row_system_id_security";
    static public final String RISK_ROW_SYSTEM_ID_THIRD_PARTY_LIABILITY = "risk_row_system_id_third_party_liability";
}
