
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.survey;

public interface InternalOperationalIntegrity
{
    static public final String RISK_GROUP_CONFLICT_OF_INTEREST = "risk_group_conflict_of_interest";
    static public final String RISK_GROUP_EMPLOYEE_FRAUD = "risk_group_employee_fraud";
    static public final String RISK_NAME_CONFLICT_OF_INTEREST = "risk_name_conflict_of_interest";
    static public final String RISK_NAME_EMPLOYEE_FRAUD = "risk_name_employee_fraud";
    static public final String RISK_RESPONSE_CONFLICT_OF_INTEREST = "risk_response_conflict_of_interest";
    static public final String RISK_RESPONSE_EMPLOYEE_FRAUD = "risk_response_employee_fraud";
    static public final String RISK_ROW_SYSTEM_ID_CONFLICT_OF_INTEREST = "risk_row_system_id_conflict_of_interest";
    static public final String RISK_ROW_SYSTEM_ID_EMPLOYEE_FRAUD = "risk_row_system_id_employee_fraud";
}
