
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.app;

public interface Submit
{
    static public final String CONFIRM = "confirm";
}
