
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.query;

public interface Cts
{
    static public final String GET_ALL_CONTACTS = "cts.get-all-contacts";
    static public final String GET_ALL_ORG_ADRESSES = "cts.get-all-org-adresses";
    static public final String GET_ALL_ORG_CLASSIFICATIONS = "cts.get-all-org-classifications";
    static public final String GET_ALL_ORGS = "cts.get-all-orgs";
    static public final String GET_ALL_PERSON_ORG_RELATIONSHIPS = "cts.get-all-person-org-relationships";
    static public final String GET_ALL_PERSONS = "cts.get-all-persons";
    static public final String GET_ALL_STUDIES = "cts.get-all-studies";
    static public final String GET_ALL_STUDY_ORG_RELATIONSHIPS = "cts.get-all-study-org-relationships";
    static public final String GET_ALL_STUDY_PERSON_RELATIONSHIPS = "cts.get-all-study-person-relationships";
    static public final String GET_BOOK_INFO = "cts.get-book-info";
    static public final String GET_CONTACT_INFO_BY_ID = "cts.get-contact-info-by-id";
    static public final String GET_PERSON_BY_STUDY_ID = "cts.get-person-by-study-id";
    static public final String GET_PERSONNEL_BY_STUDY_ID = "cts.get-personnel-by-study-id";
    static public final String GET_PERSONS_BY_STUDY = "cts.get-persons-by-study";
    static public final String GET_RELATED_ORGS_BY_STUDY_ID = "cts.get-related-orgs-by-study-id";
    static public final String GET_SUBJECTS_BY_STUDY_ID = "cts.get-subjects-by-study-id";
    static public final String LOGIN_USER_INFO = "cts.login-user-info";
}
