
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.query;

public interface Person
{
    static public final String AUTHENTICATED_USER_INFO = "person.authenticated-user-info";
    static public final String COORDINATOR_SELF_INFO = "person.coordinator-self-info";
    static public final String GET_ACTIVE_STUDY_AS_SUBJECT = "person.get-active-study-as-subject";
    static public final String GET_CONTACT_INFO_BY_PERSON_ID = "person.get-contact-info-by-person-id";
    static public final String GET_PROFILE_BY_PERSON_ID = "person.get-profile-by-person-id";
    static public final String SELF_ACTIVE_ORGS = "person.self-active-orgs";
    static public final String SELF_ACTIVE_STUDIES = "person.self-active-studies";
    static public final String SELF_CONTACT_INFO = "person.self-contact-info";
    static public final String SELF_INFO = "person.self-info";
    static public final String SELF_NOTES = "person.self-notes";
}
