
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.query;

public interface Study
{
    static public final String GET_PERSONNEL_BY_STUDY_ID = "study.get-personnel-by-study-id";
    static public final String GET_SELF_STUDY_INFO = "study.get-self-study-info";
    static public final String GET_SELF_STUDY_SITES = "study.get-self-study-sites";
    static public final String GET_SELF_STUDY_SPONSORS = "study.get-self-study-sponsors";
    static public final String GET_SITES_BY_STUDY_ID = "study.get-sites-by-study-id";
    static public final String GET_SPONSORS_BY_STUDY_ID = "study.get-sponsors-by-study-id";
    static public final String GET_STUDY_INFO_BY_ID = "study.get-study-info-by-id";
    static public final String GET_SUBJECTS_BY_STUDY_ID = "study.get-subjects-by-study-id";
}
