
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql;

public interface QueryDefn
{
    static public final String ORG = "org";
    static public final String PERSON = "person";
    static public final String STUDY = "study";
}
