
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.study;

public interface Profile
{
    static public final String ACTUAL_END_DATE = "actual_end_date";
    static public final String IRB_APPROVAL_DATE = "irb_approval_date";
    static public final String IRB_EXPIRATION_DATE = "irb_expiration_date";
    static public final String IRB_NAME = "irb_name";
    static public final String IRB_NUMBER = "irb_number";
    static public final String PRIMARY_EMAIL = "primary_email";
    static public final String PRIMARY_PHONE = "primary_phone";
    static public final String SPONSOR_ORG_NAME = "sponsor_org_name";
    static public final String START_DATE = "start_date";
    static public final String STUDY_CODE = "study_code";
    static public final String STUDY_DESCR = "study_descr";
    static public final String STUDY_NAME = "study_name";
    static public final String STUDY_PHASE = "study_phase";
    static public final String STUDY_STATUS = "study_status";
    static public final String TARGET_END_DATE = "target_end_date";
}
