
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db;

public interface Enum
{
    static public final int BUSINESS_UNIT = 11;
    static public final int DIVISION = 10;
    static public final int JOB_FUNCTION = 7;
    static public final int JOB_LOCATION = 8;
    static public final int JOB_TITLE = 9;
    static public final int LOOKUP_RESULT_TYPE = 0;
    static public final int RECORD_STATUS = 1;
    static public final int RISK_RATING = 6;
}
