
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db;

public interface Table
{
    static public final int CURRENT_ENVIRONMENT = 5;
    static public final int RESPONDENT = 2;
    static public final int RISK_RESPONSE = 3;
    static public final int VISITED_PAGE = 4;
}
