
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema;

public interface Db
{
    static public final String CURRENT_ENVIRONMENT = "schema.db.Current_Environment";
    static public final String RESPONDENT = "schema.db.Respondent";
}
