
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db;

public interface Enum
{
    static public final int BLOOD_TYPE = 8;
    static public final int CONTACT_ADDRESS_TYPE = 4;
    static public final int CONTACT_EMAIL_TYPE = 6;
    static public final int CONTACT_METHOD_TYPE = 3;
    static public final int CONTACT_TELEPHONE_TYPE = 5;
    static public final int DEFAULT_QUESTIONS = 35;
    static public final int ETHNICITY_TYPE = 9;
    static public final int FIELD_CHANGE_TYPE = 27;
    static public final int GENDER_TYPE = 10;
    static public final int LANGUAGE_TYPE = 11;
    static public final int LOOKUP_RESULT_TYPE = 0;
    static public final int MARITAL_STATUS_TYPE = 12;
    static public final int MEASUREMENT_UNIT_TYPE = 28;
    static public final int MONTH_OF_YEAR = 29;
    static public final int NAME_PREFIX_TYPE = 13;
    static public final int ORG_IDENTIFIER_TYPE = 21;
    static public final int ORG_INDUSTRY_TYPE = 22;
    static public final int ORG_LEVEL_TYPE = 23;
    static public final int ORG_OWNERSHIP_TYPE = 24;
    static public final int ORG_RELATIONSHIP_STATUS = 74;
    static public final int ORG_RELATIONSHIP_TYPE = 73;
    static public final int ORG_TYPE = 25;
    static public final int PERSONORG_REL_STATUS = 61;
    static public final int PERSONORG_REL_TYPE = 18;
    static public final int PERSON_FLAG_STATUS = 50;
    static public final int PERSON_INDICATION_TYPE = 15;
    static public final int PERSON_LICENSE_TYPE = 16;
    static public final int PERSON_LOGIN_STATUS = 54;
    static public final int PERSON_NOTE_TYPE = 7;
    static public final int PERSON_RELATIONSHIP_STATUS = 56;
    static public final int PERSON_RELATIONSHIP_TYPE = 17;
    static public final int PERSON_ROLE_STATUS = 59;
    static public final int PERSON_ROLE_TYPE = 19;
    static public final int PERSON_TYPE = 14;
    static public final int RECORD_STATE = 2;
    static public final int RECORD_STATUS = 1;
    static public final int SESSION_STATUS_TYPE = 30;
    static public final int STAFF_SPECIALITY_TYPE = 32;
    static public final int STUDYORG_REL_STATUS = 79;
    static public final int STUDYORG_RELATION_TYPE = 39;
    static public final int STUDYPERSON_REL_STATUS = 81;
    static public final int STUDYPERSON_RELATION_TYPE = 40;
    static public final int STUDY_DURATION_TYPE = 37;
    static public final int STUDY_STAGE_TYPE = 36;
    static public final int STUDY_STATUS = 38;
    static public final int TABLE_ACTIVITY_TYPE = 26;
    static public final int US_STATE_TYPE = 31;
}
