
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db;

public interface Table
{
    static public final int ORG = 68;
    static public final int ORG_ADDRESS = 69;
    static public final int ORG_CLASSIFICATION = 71;
    static public final int ORG_CONTACT = 72;
    static public final int ORG_IDENTIFIER = 73;
    static public final int ORG_INDUSTRY = 74;
    static public final int ORG_NOTE = 70;
    static public final int ORG_PERSONID_SRC_TYPE = 75;
    static public final int ORG_RELATIONSHIP = 78;
    static public final int ORG_ROLE_DECLARATION = 79;
    static public final int PER_ETHNICITY_ID_SET = 43;
    static public final int PER_LANGUAGE_ID_SET = 44;
    static public final int PERSON = 42;
    static public final int PERSONORG_RELATIONSHIP = 64;
    static public final int PERSONORG_RELATIONSHIP_MAP = 66;
    static public final int PERSONSESSION_ACTIVITY = 84;
    static public final int PERSONSESSION_VIEW_COUNT = 85;
    static public final int PERSONSTUDY_RELATIONSHIP = 65;
    static public final int PERSON_ADDRESS = 45;
    static public final int PERSON_CLASSIFICATION = 47;
    static public final int PERSON_CONTACT = 48;
    static public final int PERSON_ETHNICITY = 49;
    static public final int PERSON_FLAG = 52;
    static public final int PERSON_IDENTIFIER = 53;
    static public final int PERSON_LANGUAGE = 54;
    static public final int PERSON_LOGIN = 56;
    static public final int PERSON_NOTE = 46;
    static public final int PERSON_RELATIONSHIP = 58;
    static public final int PERSON_RELATIONSHIP_MAP = 59;
    static public final int PERSON_ROLE = 61;
    static public final int PERSON_SESSION = 83;
    static public final int STAFF_LICENSE = 67;
    static public final int STUDY = 80;
    static public final int STUDYORG_RELATIONSHIP = 81;
}
