
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db;

public interface Table
{
    static public final int ORG = 65;
    static public final int ORG_ADDRESS = 66;
    static public final int ORG_CLASSIFICATION = 68;
    static public final int ORG_CONTACT = 69;
    static public final int ORG_IDENTIFIER = 70;
    static public final int ORG_INDUSTRY = 71;
    static public final int ORG_NOTE = 67;
    static public final int ORG_PERSONID_SRC_TYPE = 72;
    static public final int ORG_RELATIONSHIP = 75;
    static public final int ORG_ROLE_DECLARATION = 76;
    static public final int PER_ETHNICITY_ID_SET = 42;
    static public final int PER_LANGUAGE_ID_SET = 43;
    static public final int PERSON = 41;
    static public final int PERSONORG_RELATIONSHIP = 62;
    static public final int PERSONORG_RELATIONSHIP_MAP = 63;
    static public final int PERSONSESSION_ACTIVITY = 83;
    static public final int PERSONSESSION_VIEW_COUNT = 84;
    static public final int PERSON_ADDRESS = 44;
    static public final int PERSON_CLASSIFICATION = 46;
    static public final int PERSON_CONTACT = 47;
    static public final int PERSON_ETHNICITY = 48;
    static public final int PERSON_FLAG = 51;
    static public final int PERSON_IDENTIFIER = 52;
    static public final int PERSON_LANGUAGE = 53;
    static public final int PERSON_LOGIN = 55;
    static public final int PERSON_NOTE = 45;
    static public final int PERSON_RELATIONSHIP = 57;
    static public final int PERSON_RELATIONSHIP_MAP = 58;
    static public final int PERSON_ROLE = 60;
    static public final int PERSON_SESSION = 82;
    static public final int STAFF_LICENSE = 64;
    static public final int STUDY = 77;
    static public final int STUDYORG_RELATIONSHIP = 78;
    static public final int STUDYPERSON_RELATIONSHIP = 80;
}
