
/* this file is generated by com.netspective.sparx.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package auto.dcb.form.acl;

import com.netspective.sparx.form.*;
import com.netspective.sparx.form.field.*;
import com.netspective.sparx.form.field.type.*;

public class RoleContext
{
    public static final String DIALOG_ID = "form.acl.role";
    private DialogContext dialogContext;
    private DialogFieldStates fieldStates;

    public RoleContext(DialogContext dc)
    {
        this.dialogContext = dc;
        this.fieldStates = dc.getFieldStates();
    }

    public DialogContext getDialogContext() { return dialogContext; }


	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getRoleListState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("role_list"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getRoleList() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getRoleListState().getValue(); }
	public DialogFieldFlags getRoleListStateFlags() { return getRoleListState().getStateFlags(); }
	public String getRoleListPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.role_list"); }
	public String getRoleListPublicRequestParam() { return dialogContext.getRequest().getParameter("role_list"); }
	public com.netspective.sparx.form.field.type.SelectField getRoleListField() { return (com.netspective.sparx.form.field.type.SelectField) getRoleListState().getField(); }

}
