
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface AssetLoan
{
    static public final String ASSET_ID = "asset_id";
    static public final String ASSET_LOAN_ID = "asset_loan_id";
    static public final String BORROWER_ID = "borrower_id";
    static public final String LOAN_BEGIN_DATE = "loan_begin_date";
    static public final String LOAN_END_DATE = "loan_end_date";
    static public final String LOAN_TYPE = "loan_type";
    static public final String RETURNED = "returned";
}
