
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface Asset
{
    static public final String ASSET_ID = "asset_id";
    static public final String NAME = "name";
    static public final String QUANTITY = "quantity";
    static public final String TYPE = "type";
}
