
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface BookInfo
{
    static public final String AUTHOR = "author";
    static public final String GENRE = "genre";
    static public final String ID = "id";
    static public final String ISBN = "isbn";
    static public final String NAME = "name";
}
