
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface Borrower
{
    static public final String BORROWER_ID = "borrower_id";
    static public final String FIRST_NAME = "first_name";
    static public final String LAST_NAME = "last_name";
}
