
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.query;

public interface Petstore
{
    static public final String GETCARTDETAIL = "petstore.getCartDetail";
    static public final String GETITEMS = "petstore.getItems";
    static public final String GETPRODUCTDETAIL = "petstore.getProductDetail";
    static public final String GETPRODUCTNAME = "petstore.getProductName";
    static public final String GETPRODUCTS = "petstore.getProducts";
}
