
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.templates;

public interface BodyFile
{
    static public final String BIRTH_DATE = "birth_date";
    static public final String FULL_NAME = "full_name";
}
