
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema;

public interface Db
{
    static public final String BOOK_INFO = "schema.db.Book_Info";
}
