
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema;

public interface Db
{
    static public final String ASSET = "schema.db.Asset";
    static public final String ASSET_LOAN = "schema.db.Asset_Loan";
    static public final String BORROWER = "schema.db.Borrower";
}
