
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql;

public interface QueryDefn
{
    static public final String LIBRARY = "library";
}
