
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.navigation;

public interface App
{
    static public final String CART = "/cart";
    static public final String CATEGORY = "/category";
    static public final String CHECKOUT = "/checkout";
    static public final String CONSOLE = "/console";
    static public final String HOME = "/home";
    static public final String PLACEORDER = "/placeorder";
    static public final String POPUP = "/popup";
    static public final String PRODUCT = "/product";
    static public final String PRODUCTDETAILS = "/productdetails";
    static public final String SIGNIN = "/signin";
}
