
/* this file is generated by com.netspective.sparx.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package auto.dcb.study;

import com.netspective.sparx.form.*;
import com.netspective.sparx.form.field.*;
import com.netspective.sparx.form.field.type.*;

public class NewSponsorContext
{
    public static final String DIALOG_ID = "study.new-sponsor";
    private DialogContext dialogContext;
    private DialogContext.DialogFieldStates fieldStates;

    public NewSponsorContext(DialogContext dc)
    {
        this.dialogContext = dc;
        this.fieldStates = dc.getFieldStates();
    }

    public DialogContext getDialogContext() { return dialogContext; }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getOrgNameState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("org_name"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getOrgName() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getOrgNameState().getValue(); }
	public DialogFieldFlags getOrgNameStateFlags() { return getOrgNameState().getStateFlags(); }
	public String getOrgNamePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.org_name"); }
	public String getOrgNamePublicRequestParam() { return dialogContext.getRequest().getParameter("org_name"); }
	public com.netspective.sparx.form.field.type.TextField getOrgNameField() { return (com.netspective.sparx.form.field.type.TextField) getOrgNameState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getOrgCodeState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("org_code"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getOrgCode() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getOrgCodeState().getValue(); }
	public DialogFieldFlags getOrgCodeStateFlags() { return getOrgCodeState().getStateFlags(); }
	public String getOrgCodePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.org_code"); }
	public String getOrgCodePublicRequestParam() { return dialogContext.getRequest().getParameter("org_code"); }
	public com.netspective.sparx.form.field.type.TextField getOrgCodeField() { return (com.netspective.sparx.form.field.type.TextField) getOrgCodeState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getOrgAbbrevState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("org_abbrev"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getOrgAbbrev() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getOrgAbbrevState().getValue(); }
	public DialogFieldFlags getOrgAbbrevStateFlags() { return getOrgAbbrevState().getStateFlags(); }
	public String getOrgAbbrevPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.org_abbrev"); }
	public String getOrgAbbrevPublicRequestParam() { return dialogContext.getRequest().getParameter("org_abbrev"); }
	public com.netspective.sparx.form.field.type.TextField getOrgAbbrevField() { return (com.netspective.sparx.form.field.type.TextField) getOrgAbbrevState().getField(); }


	public com.netspective.sparx.form.field.type.TextField.TextFieldState getAddressNameState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("address_name"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getAddressName() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getAddressNameState().getValue(); }
	public DialogFieldFlags getAddressNameStateFlags() { return getAddressNameState().getStateFlags(); }
	public String getAddressNamePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.address_name"); }
	public String getAddressNamePublicRequestParam() { return dialogContext.getRequest().getParameter("address_name"); }
	public com.netspective.sparx.form.field.type.TextField getAddressNameField() { return (com.netspective.sparx.form.field.type.TextField) getAddressNameState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getLine1State() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("line1"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getLine1() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getLine1State().getValue(); }
	public DialogFieldFlags getLine1StateFlags() { return getLine1State().getStateFlags(); }
	public String getLine1PrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.line1"); }
	public String getLine1PublicRequestParam() { return dialogContext.getRequest().getParameter("line1"); }
	public com.netspective.sparx.form.field.type.TextField getLine1Field() { return (com.netspective.sparx.form.field.type.TextField) getLine1State().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getLine2State() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("line2"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getLine2() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getLine2State().getValue(); }
	public DialogFieldFlags getLine2StateFlags() { return getLine2State().getStateFlags(); }
	public String getLine2PrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.line2"); }
	public String getLine2PublicRequestParam() { return dialogContext.getRequest().getParameter("line2"); }
	public com.netspective.sparx.form.field.type.TextField getLine2Field() { return (com.netspective.sparx.form.field.type.TextField) getLine2State().getField(); }

	public com.netspective.sparx.form.field.DialogField.State getCityStateZipState() { return (com.netspective.sparx.form.field.DialogField.State) fieldStates.getState("cityStateZip"); }
	public com.netspective.sparx.form.field.DialogField.State.BasicStateValue getCityStateZip() { return (com.netspective.sparx.form.field.DialogField.State.BasicStateValue) getCityStateZipState().getValue(); }
	public DialogFieldFlags getCityStateZipStateFlags() { return getCityStateZipState().getStateFlags(); }
	public String getCityStateZipPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.cityStateZip"); }
	public String getCityStateZipPublicRequestParam() { return dialogContext.getRequest().getParameter("cityStateZip"); }
	public com.netspective.sparx.form.field.DialogField getCityStateZipField() { return (com.netspective.sparx.form.field.DialogField) getCityStateZipState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getCityStateZip_cityState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("cityStateZip.city"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getCityStateZip_city() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getCityStateZip_cityState().getValue(); }
	public DialogFieldFlags getCityStateZip_cityStateFlags() { return getCityStateZip_cityState().getStateFlags(); }
	public String getCityStateZip_cityPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.cityStateZip.city"); }
	public String getCityStateZip_cityPublicRequestParam() { return dialogContext.getRequest().getParameter("cityStateZip.city"); }
	public com.netspective.sparx.form.field.type.TextField getCityStateZip_cityField() { return (com.netspective.sparx.form.field.type.TextField) getCityStateZip_cityState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getCityStateZip_stateState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("cityStateZip.state"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getCityStateZip_state() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getCityStateZip_stateState().getValue(); }
	public DialogFieldFlags getCityStateZip_stateStateFlags() { return getCityStateZip_stateState().getStateFlags(); }
	public String getCityStateZip_statePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.cityStateZip.state"); }
	public String getCityStateZip_statePublicRequestParam() { return dialogContext.getRequest().getParameter("cityStateZip.state"); }
	public com.netspective.sparx.form.field.type.SelectField getCityStateZip_stateField() { return (com.netspective.sparx.form.field.type.SelectField) getCityStateZip_stateState().getField(); }

	public com.netspective.sparx.form.field.type.ZipCodeField.ZipCodeFieldState getCityStateZip_zipState() { return (com.netspective.sparx.form.field.type.ZipCodeField.ZipCodeFieldState) fieldStates.getState("cityStateZip.zip"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getCityStateZip_zip() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getCityStateZip_zipState().getValue(); }
	public DialogFieldFlags getCityStateZip_zipStateFlags() { return getCityStateZip_zipState().getStateFlags(); }
	public String getCityStateZip_zipPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.cityStateZip.zip"); }
	public String getCityStateZip_zipPublicRequestParam() { return dialogContext.getRequest().getParameter("cityStateZip.zip"); }
	public com.netspective.sparx.form.field.type.ZipCodeField getCityStateZip_zipField() { return (com.netspective.sparx.form.field.type.ZipCodeField) getCityStateZip_zipState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getCountryState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("country"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getCountry() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getCountryState().getValue(); }
	public DialogFieldFlags getCountryStateFlags() { return getCountryState().getStateFlags(); }
	public String getCountryPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.country"); }
	public String getCountryPublicRequestParam() { return dialogContext.getRequest().getParameter("country"); }
	public com.netspective.sparx.form.field.type.TextField getCountryField() { return (com.netspective.sparx.form.field.type.TextField) getCountryState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getTimeZoneState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("time_zone"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getTimeZone() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getTimeZoneState().getValue(); }
	public DialogFieldFlags getTimeZoneStateFlags() { return getTimeZoneState().getStateFlags(); }
	public String getTimeZonePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.time_zone"); }
	public String getTimeZonePublicRequestParam() { return dialogContext.getRequest().getParameter("time_zone"); }
	public com.netspective.sparx.form.field.type.TextField getTimeZoneField() { return (com.netspective.sparx.form.field.type.TextField) getTimeZoneState().getField(); }


	public com.netspective.sparx.form.field.DialogField.State getPrimaryState() { return (com.netspective.sparx.form.field.DialogField.State) fieldStates.getState("primary"); }
	public com.netspective.sparx.form.field.DialogField.State.BasicStateValue getPrimary() { return (com.netspective.sparx.form.field.DialogField.State.BasicStateValue) getPrimaryState().getValue(); }
	public DialogFieldFlags getPrimaryStateFlags() { return getPrimaryState().getStateFlags(); }
	public String getPrimaryPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.primary"); }
	public String getPrimaryPublicRequestParam() { return dialogContext.getRequest().getParameter("primary"); }
	public com.netspective.sparx.form.field.DialogField getPrimaryField() { return (com.netspective.sparx.form.field.DialogField) getPrimaryState().getField(); }

	public com.netspective.sparx.form.field.type.PhoneField.State getPrimary_phoneState() { return (com.netspective.sparx.form.field.type.PhoneField.State) fieldStates.getState("primary.phone"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getPrimary_phone() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getPrimary_phoneState().getValue(); }
	public DialogFieldFlags getPrimary_phoneStateFlags() { return getPrimary_phoneState().getStateFlags(); }
	public String getPrimary_phonePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.primary.phone"); }
	public String getPrimary_phonePublicRequestParam() { return dialogContext.getRequest().getParameter("primary.phone"); }
	public com.netspective.sparx.form.field.type.PhoneField getPrimary_phoneField() { return (com.netspective.sparx.form.field.type.PhoneField) getPrimary_phoneState().getField(); }

	public com.netspective.sparx.form.field.type.PhoneField.State getPrimary_faxState() { return (com.netspective.sparx.form.field.type.PhoneField.State) fieldStates.getState("primary.fax"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getPrimary_fax() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getPrimary_faxState().getValue(); }
	public DialogFieldFlags getPrimary_faxStateFlags() { return getPrimary_faxState().getStateFlags(); }
	public String getPrimary_faxPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.primary.fax"); }
	public String getPrimary_faxPublicRequestParam() { return dialogContext.getRequest().getParameter("primary.fax"); }
	public com.netspective.sparx.form.field.type.PhoneField getPrimary_faxField() { return (com.netspective.sparx.form.field.type.PhoneField) getPrimary_faxState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getEmailState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("email"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getEmail() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getEmailState().getValue(); }
	public DialogFieldFlags getEmailStateFlags() { return getEmailState().getStateFlags(); }
	public String getEmailPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.email"); }
	public String getEmailPublicRequestParam() { return dialogContext.getRequest().getParameter("email"); }
	public com.netspective.sparx.form.field.type.TextField getEmailField() { return (com.netspective.sparx.form.field.type.TextField) getEmailState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getWebsiteState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("website"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getWebsite() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getWebsiteState().getValue(); }
	public DialogFieldFlags getWebsiteStateFlags() { return getWebsiteState().getStateFlags(); }
	public String getWebsitePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.website"); }
	public String getWebsitePublicRequestParam() { return dialogContext.getRequest().getParameter("website"); }
	public com.netspective.sparx.form.field.type.TextField getWebsiteField() { return (com.netspective.sparx.form.field.type.TextField) getWebsiteState().getField(); }

}
