
/* this file is generated by com.netspective.sparx.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package auto.dcb.study;

import com.netspective.sparx.form.*;
import com.netspective.sparx.form.field.*;
import com.netspective.sparx.form.field.type.*;

public class ProfileContext
{
    public static final String DIALOG_ID = "study.profile";
    private DialogContext dialogContext;
    private DialogContext.DialogFieldStates fieldStates;

    public ProfileContext(DialogContext dc)
    {
        this.dialogContext = dc;
        this.fieldStates = dc.getFieldStates();
    }

    public DialogContext getDialogContext() { return dialogContext; }


	public com.netspective.sparx.form.field.type.TextField.TextFieldState getStudyIdState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("study_id"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getStudyId() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getStudyIdState().getValue(); }
	public DialogFieldFlags getStudyIdStateFlags() { return getStudyIdState().getStateFlags(); }
	public String getStudyIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.study_id"); }
	public String getStudyIdPublicRequestParam() { return dialogContext.getRequest().getParameter("study_id"); }
	public com.netspective.sparx.form.field.type.TextField getStudyIdField() { return (com.netspective.sparx.form.field.type.TextField) getStudyIdState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getStudyNameState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("study_name"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getStudyName() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getStudyNameState().getValue(); }
	public DialogFieldFlags getStudyNameStateFlags() { return getStudyNameState().getStateFlags(); }
	public String getStudyNamePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.study_name"); }
	public String getStudyNamePublicRequestParam() { return dialogContext.getRequest().getParameter("study_name"); }
	public com.netspective.sparx.form.field.type.TextField getStudyNameField() { return (com.netspective.sparx.form.field.type.TextField) getStudyNameState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getStudyCodeState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("study_code"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getStudyCode() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getStudyCodeState().getValue(); }
	public DialogFieldFlags getStudyCodeStateFlags() { return getStudyCodeState().getStateFlags(); }
	public String getStudyCodePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.study_code"); }
	public String getStudyCodePublicRequestParam() { return dialogContext.getRequest().getParameter("study_code"); }
	public com.netspective.sparx.form.field.type.TextField getStudyCodeField() { return (com.netspective.sparx.form.field.type.TextField) getStudyCodeState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getStudyDescrState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("study_descr"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getStudyDescr() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getStudyDescrState().getValue(); }
	public DialogFieldFlags getStudyDescrStateFlags() { return getStudyDescrState().getStateFlags(); }
	public String getStudyDescrPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.study_descr"); }
	public String getStudyDescrPublicRequestParam() { return dialogContext.getRequest().getParameter("study_descr"); }
	public com.netspective.sparx.form.field.type.MemoField getStudyDescrField() { return (com.netspective.sparx.form.field.type.MemoField) getStudyDescrState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getStudyStatusState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("study_status"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getStudyStatus() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getStudyStatusState().getValue(); }
	public DialogFieldFlags getStudyStatusStateFlags() { return getStudyStatusState().getStateFlags(); }
	public String getStudyStatusPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.study_status"); }
	public String getStudyStatusPublicRequestParam() { return dialogContext.getRequest().getParameter("study_status"); }
	public com.netspective.sparx.form.field.type.SelectField getStudyStatusField() { return (com.netspective.sparx.form.field.type.SelectField) getStudyStatusState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getStudyStageState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("study_stage"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getStudyStage() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getStudyStageState().getValue(); }
	public DialogFieldFlags getStudyStageStateFlags() { return getStudyStageState().getStateFlags(); }
	public String getStudyStagePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.study_stage"); }
	public String getStudyStagePublicRequestParam() { return dialogContext.getRequest().getParameter("study_stage"); }
	public com.netspective.sparx.form.field.type.SelectField getStudyStageField() { return (com.netspective.sparx.form.field.type.SelectField) getStudyStageState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getSponsorOrgNameState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("sponsor_org_name"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getSponsorOrgName() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getSponsorOrgNameState().getValue(); }
	public DialogFieldFlags getSponsorOrgNameStateFlags() { return getSponsorOrgNameState().getStateFlags(); }
	public String getSponsorOrgNamePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.sponsor_org_name"); }
	public String getSponsorOrgNamePublicRequestParam() { return dialogContext.getRequest().getParameter("sponsor_org_name"); }
	public com.netspective.sparx.form.field.type.SelectField getSponsorOrgNameField() { return (com.netspective.sparx.form.field.type.SelectField) getSponsorOrgNameState().getField(); }


	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState getStartDateState() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState) fieldStates.getState("start_date"); }
	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue getStartDate() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue) getStartDateState().getValue(); }
	public DialogFieldFlags getStartDateStateFlags() { return getStartDateState().getStateFlags(); }
	public String getStartDatePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.start_date"); }
	public String getStartDatePublicRequestParam() { return dialogContext.getRequest().getParameter("start_date"); }
	public com.netspective.sparx.form.field.type.DateTimeField getStartDateField() { return (com.netspective.sparx.form.field.type.DateTimeField) getStartDateState().getField(); }

	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState getTargetEndDateState() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState) fieldStates.getState("target_end_date"); }
	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue getTargetEndDate() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue) getTargetEndDateState().getValue(); }
	public DialogFieldFlags getTargetEndDateStateFlags() { return getTargetEndDateState().getStateFlags(); }
	public String getTargetEndDatePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.target_end_date"); }
	public String getTargetEndDatePublicRequestParam() { return dialogContext.getRequest().getParameter("target_end_date"); }
	public com.netspective.sparx.form.field.type.DateTimeField getTargetEndDateField() { return (com.netspective.sparx.form.field.type.DateTimeField) getTargetEndDateState().getField(); }

	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState getActualEndDateState() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState) fieldStates.getState("actual_end_date"); }
	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue getActualEndDate() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue) getActualEndDateState().getValue(); }
	public DialogFieldFlags getActualEndDateStateFlags() { return getActualEndDateState().getStateFlags(); }
	public String getActualEndDatePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.actual_end_date"); }
	public String getActualEndDatePublicRequestParam() { return dialogContext.getRequest().getParameter("actual_end_date"); }
	public com.netspective.sparx.form.field.type.DateTimeField getActualEndDateField() { return (com.netspective.sparx.form.field.type.DateTimeField) getActualEndDateState().getField(); }


	public com.netspective.sparx.form.field.type.TextField.TextFieldState getIrbNameState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("irb_name"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getIrbName() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getIrbNameState().getValue(); }
	public DialogFieldFlags getIrbNameStateFlags() { return getIrbNameState().getStateFlags(); }
	public String getIrbNamePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.irb_name"); }
	public String getIrbNamePublicRequestParam() { return dialogContext.getRequest().getParameter("irb_name"); }
	public com.netspective.sparx.form.field.type.TextField getIrbNameField() { return (com.netspective.sparx.form.field.type.TextField) getIrbNameState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getIrbNumberState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("irb_number"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getIrbNumber() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getIrbNumberState().getValue(); }
	public DialogFieldFlags getIrbNumberStateFlags() { return getIrbNumberState().getStateFlags(); }
	public String getIrbNumberPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.irb_number"); }
	public String getIrbNumberPublicRequestParam() { return dialogContext.getRequest().getParameter("irb_number"); }
	public com.netspective.sparx.form.field.type.TextField getIrbNumberField() { return (com.netspective.sparx.form.field.type.TextField) getIrbNumberState().getField(); }

	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState getIrbApprovalDateState() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState) fieldStates.getState("irb_approval_date"); }
	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue getIrbApprovalDate() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue) getIrbApprovalDateState().getValue(); }
	public DialogFieldFlags getIrbApprovalDateStateFlags() { return getIrbApprovalDateState().getStateFlags(); }
	public String getIrbApprovalDatePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.irb_approval_date"); }
	public String getIrbApprovalDatePublicRequestParam() { return dialogContext.getRequest().getParameter("irb_approval_date"); }
	public com.netspective.sparx.form.field.type.DateTimeField getIrbApprovalDateField() { return (com.netspective.sparx.form.field.type.DateTimeField) getIrbApprovalDateState().getField(); }

	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState getIrbExpirationDateState() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState) fieldStates.getState("irb_expiration_date"); }
	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue getIrbExpirationDate() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue) getIrbExpirationDateState().getValue(); }
	public DialogFieldFlags getIrbExpirationDateStateFlags() { return getIrbExpirationDateState().getStateFlags(); }
	public String getIrbExpirationDatePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.irb_expiration_date"); }
	public String getIrbExpirationDatePublicRequestParam() { return dialogContext.getRequest().getParameter("irb_expiration_date"); }
	public com.netspective.sparx.form.field.type.DateTimeField getIrbExpirationDateField() { return (com.netspective.sparx.form.field.type.DateTimeField) getIrbExpirationDateState().getField(); }

}
