
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema;

public interface Db
{
    static public final String ACCOUNT = "schema.db.Account";
    static public final String BANNER_DATA = "schema.db.Banner_Data";
    static public final String CATEGORY = "schema.db.Category";
    static public final String ITEM = "schema.db.Item";
    static public final String LINEITEM = "schema.db.LineItem";
    static public final String ORDERSTATUS = "schema.db.OrderStatus";
    static public final String ORDERS = "schema.db.Orders";
    static public final String PRODUCT = "schema.db.Product";
    static public final String PROFILE = "schema.db.Profile";
    static public final String SUPPLIER = "schema.db.Supplier";
}
