
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.site;

public interface AddressInfo
{
    static public final String ADDRESS_NAME = "address_name";
    static public final String CITYSTATEZIP = "cityStateZip";
    static public final String LINE1 = "line1";
    static public final String LINE2 = "line2";
    static public final String ORG_ID = "org_id";
}
