
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.site;

public interface ContactInfo
{
    static public final String CONTACTTYPE = "contactType";
    static public final String ID = "id";
    static public final String METHOD_VALUE = "method_value";
    static public final String ORG_ID = "org_id";
}
