
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.query;

public interface Library
{
    static public final String ASSET_NAMES_FOR_SELECT_FIELD_CHOICES = "library.asset-names-for-select-field-choices";
    static public final String BORROWER_NAMES_FOR_SELECT_FIELD_CHOICES = "library.borrower-names-for-select-field-choices";
    static public final String GET_ALL_ASSET_LOANS = "library.get-all-asset-loans";
    static public final String GET_ALL_ASSETS = "library.get-all-assets";
    static public final String GET_ALL_BORROWERS = "library.get-all-borrowers";
    static public final String GET_ASSET_LOANS = "library.get-asset-loans";
    static public final String GET_BORROWER_LOANS = "library.get-borrower-loans";
}
