
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.query;

public interface Library
{
    static public final String GET_ALL_BOOKS = "library.get-all-books";
}
