
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Account
{
    static public final int ACCOUNT_ID = 0;
    static public final int ADDR1 = 6;
    static public final int ADDR2 = 7;
    static public final int CITY = 8;
    static public final int COUNTRY = 10;
    static public final int EMAIL = 2;
    static public final int FIRST_NAME = 3;
    static public final int LAST_NAME = 4;
    static public final int PASSWORD = 1;
    static public final int PHONE = 11;
    static public final int STATE = 9;
    static public final int STATUS = 5;
}
