
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface BannerData
{
    static public final int BANNER_DATA_ID = 0;
    static public final int BANNER_NAME = 1;
}
