
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Category
{
    static public final int CATEGORY_ID = 0;
    static public final int DESCR = 2;
    static public final int NAME = 1;
}
