
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Item
{
    static public final int ATTR1 = 9;
    static public final int ATTR2 = 10;
    static public final int ATTR3 = 11;
    static public final int DESCR = 7;
    static public final int IMAGE = 8;
    static public final int ITEM_ID = 0;
    static public final int LIST_PRICE = 2;
    static public final int NAME = 6;
    static public final int PRODUCT_ID = 1;
    static public final int STATUS = 5;
    static public final int SUPPLIER_ID = 4;
    static public final int UNIT_COST = 3;
}
