
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface LineItem
{
    static public final int ITEM_ID = 3;
    static public final int ITEMNUM = 2;
    static public final int LINEITEM_ID = 0;
    static public final int ORDERS_ID = 1;
    static public final int QUANTITY = 4;
    static public final int UNIT_PRICE = 5;
}
