
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Orders
{
    static public final int ACCOUNT_ID = 1;
    static public final int BILL_ADDR1 = 9;
    static public final int BILL_ADDR2 = 10;
    static public final int BILL_CITY = 11;
    static public final int BILL_COUNTRY = 13;
    static public final int BILL_PHONE = 14;
    static public final int BILL_STATE = 12;
    static public final int ORDER_DATE = 2;
    static public final int ORDERS_ID = 0;
    static public final int SHIP_ADDR1 = 3;
    static public final int SHIP_ADDR2 = 4;
    static public final int SHIP_CITY = 5;
    static public final int SHIP_COUNTRY = 7;
    static public final int SHIP_PHONE = 8;
    static public final int SHIP_STATE = 6;
}
