
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface OrderStatus
{
    static public final int ITEMNUM = 2;
    static public final int ORDERS_ID = 1;
    static public final int ORDERSTATUS_ID = 0;
    static public final int STATUS = 4;
    static public final int TS = 3;
}
