
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Product
{
    static public final int CATEGORY_ID = 1;
    static public final int DESCR = 3;
    static public final int NAME = 2;
    static public final int PRODUCT_ID = 0;
}
