
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Supplier
{
    static public final int ADDR1 = 3;
    static public final int ADDR2 = 4;
    static public final int CITY = 5;
    static public final int COUNTRY = 7;
    static public final int NAME = 1;
    static public final int PHONE = 8;
    static public final int STATE = 6;
    static public final int STATUS = 2;
    static public final int SUPPLIER_ID = 0;
}
