
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.query;

public interface Responses
{
    static public final String BY_PIN = "responses.by-pin";
    static public final String BY_PIN_GROUP_RISK_ID = "responses.by-pin-group-risk-id";
}
