
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.sponsor;

public interface Address
{
    static public final String ADDRESS_NAME = "address_name";
    static public final String CITYSTATEZIP = "cityStateZip";
    static public final String COUNTRY = "country";
    static public final String EMAIL = "email";
    static public final String LINE1 = "line1";
    static public final String LINE2 = "line2";
    static public final String PRIMARY = "primary";
    static public final String TIME_ZONE = "time_zone";
    static public final String WEBSITE = "website";
}
