
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.sponsor;

public interface ShortInfo
{
    static public final String ORG_ABBREV = "org_abbrev";
    static public final String ORG_CODE = "org_code";
    static public final String ORG_NAME = "org_name";
    static public final String STUDY_ID = "study_id";
}
