
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface CurrentEnvironment
{
    static public final int APPROACH = 1;
    static public final int APPROACH_EXPL = 2;
    static public final int PIN = 0;
    static public final int RISKS_DELTA = 9;
    static public final int RISKS_DELTA_EXPL = 10;
    static public final int RISKS_DEPT = 5;
    static public final int RISKS_DEPT_EXPL = 6;
    static public final int RISKS_DIV = 7;
    static public final int RISKS_DIV_EXPL = 8;
    static public final int RISKS_PRJ = 3;
    static public final int RISKS_PRJ_EXPL = 4;
}
