
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Respondent
{
    static public final int BUSINESS_UNIT = 4;
    static public final int DIVISION = 5;
    static public final int FUNCTION = 2;
    static public final int LOCATION = 3;
    static public final int LOCKED = 8;
    static public final int PIN = 0;
    static public final int TITLE = 1;
    static public final int YRS_CURRENT_POS = 7;
    static public final int YRS_FIRM = 6;
}
