
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface VisitedPage
{
    static public final int PAGE_ID = 2;
    static public final int PIN = 1;
    static public final int SYSTEM_ID = 0;
    static public final int VISIT_COUNT = 3;
}
