
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.subject;

public interface LoginInfo
{
    static public final String LOGIN_ID = "login_id";
    static public final String NEW_PASSWORD1 = "new_password1";
    static public final String NEW_PASSWORD2 = "new_password2";
    static public final String OLD_PASSWORD = "old_password";
}
