
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.subject;

public interface Profile
{
    static public final String BLOOD_TYPE_ID = "blood_type_id";
    static public final String CITYSTATEZIP = "cityStateZip";
    static public final String DATE_OF_BIRTH = "date_of_birth";
    static public final String ETHNICITY_ID = "ethnicity_id";
    static public final String FULLNAME = "fullName";
    static public final String GENDER_ID = "gender_id";
    static public final String LANGUAGE_ID = "language_id";
    static public final String LINE1 = "line1";
    static public final String LINE2 = "line2";
    static public final String MARITAL_STATUS_ID = "marital_status_id";
    static public final String ORG_ID = "org_id";
    static public final String PERSON_ID = "person_id";
    static public final String SSN = "ssn";
    static public final String STUDY_ID = "study_id";
}
