
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface AssetLoan
{
    static public final int ASSET_ID = 1;
    static public final int ASSET_LOAN_ID = 0;
    static public final int BORROWER_ID = 2;
    static public final int LOAN_BEGIN_DATE = 4;
    static public final int LOAN_END_DATE = 5;
    static public final int LOAN_TYPE = 3;
    static public final int RETURNED = 6;
}
