
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Asset
{
    static public final int ASSET_ID = 0;
    static public final int NAME = 2;
    static public final int QUANTITY = 3;
    static public final int TYPE = 1;
}
