
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface BookInfo
{
    static public final int AUTHOR = 2;
    static public final int GENRE = 3;
    static public final int ID = 0;
    static public final int ISBN = 4;
    static public final int NAME = 1;
}
