
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Borrower
{
    static public final int BORROWER_ID = 0;
    static public final int FIRST_NAME = 1;
    static public final int LAST_NAME = 2;
}
