
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface BloodType
{
    static public final int AB_NEGATIVE = 6;
    static public final int AB_POSITIVE = 5;
    static public final int A_NEGATIVE = 2;
    static public final int A_POSITIVE = 1;
    static public final int B_NEGATIVE = 4;
    static public final int B_POSITIVE = 3;
    static public final int O_NEGATIVE = 8;
    static public final int O_POSITIVE = 7;
    static public final int UNKNOWN = 0;
}
