
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface ContactEmailType
{
    static public final int BUSINESS = 0;
    static public final int HOME = 1;
    static public final int OTHER = 2;
    static public final int PRIMARY = 3;
}
