
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface ContactTelephoneType
{
    static public final int ASSISTANT = 0;
    static public final int BUSINESS = 1;
    static public final int BUSINESS_2 = 2;
    static public final int BUSINESS_FAX = 3;
    static public final int CALLBACK = 4;
    static public final int CAR = 5;
    static public final int COMPANY = 6;
    static public final int HOME = 7;
    static public final int HOME_2 = 8;
    static public final int HOME_FAX = 9;
    static public final int ISDN = 10;
    static public final int MOBILE = 11;
    static public final int OTHER = 18;
    static public final int OTHER_FAX = 12;
    static public final int PAGER = 13;
    static public final int PRIMARY = 14;
    static public final int RADIO = 15;
    static public final int TELEX = 16;
    static public final int TTY_TDD = 17;
}
