
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface ContactMethodType
{
    static public final int EMAIL__BUSINESS = 18;
    static public final int EMAIL__HOME = 19;
    static public final int EMAIL__OTHER = 20;
    static public final int EMAIL__PRIMARY = 21;
    static public final int FAX__BUSINESS = 11;
    static public final int FAX__HOME = 12;
    static public final int FAX__OTHER = 13;
    static public final int PAGER = 14;
    static public final int RADIO = 15;
    static public final int TELEPHONE__ASSISTANT = 0;
    static public final int TELEPHONE__BUSINESS = 1;
    static public final int TELEPHONE__CALLBACK = 2;
    static public final int TELEPHONE__CAR = 3;
    static public final int TELEPHONE__COMPANY = 4;
    static public final int TELEPHONE__HOME = 5;
    static public final int TELEPHONE__HOME_2 = 6;
    static public final int TELEPHONE__ISDN = 7;
    static public final int TELEPHONE__MOBILE = 8;
    static public final int TELEPHONE__OTHER = 9;
    static public final int TELEPHONE__WORK = 10;
    static public final int TELEX = 16;
    static public final int TTY_TDD = 17;
    static public final int URL = 22;
}
