
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface ContactAddressType
{
    static public final int ALTERNATE = 2;
    static public final int BILLING = 3;
    static public final int OTHER = 4;
    static public final int PRIMARY = 0;
    static public final int SECONDARY = 1;
}
