
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface DefaultQuestions
{
    static public final int ARE_YOU_A_FEMALE_WHO__IN_THE_LAST_6_WEEKS__HAS_BEEN_PREGNANT_OR_IS_NOW_PREGNANT_ = 5;
    static public final int ARE_YOU_FEELING_WELL_TODAY_ = 0;
    static public final int DO_YOU_HAVE_AN_INFECTION_NOW__OR_ARE_YOU_TAKING_ANTIBIOTICS_NOW_ = 1;
    static public final int HAVE_YOU_EVER_HAD_A_BLOOD_DISEASE_OR_A_BLEEDING_PROBLEM_ = 7;
    static public final int HAVE_YOU_EVER_TESTED_POSITIVE_FOR_HEPATITIS_ = 6;
    static public final int HAVE_YOU_EVER_USED_A_NEEDLE__EVEN_ONCE__TO_TAKE_ANY_ILLEGAL_OR_NON_PRESCRIPTION_DRUG_ = 8;
    static public final int HAVE_YOU_HAD_ORAL_SURGERY_IN_THE_LAST_3_DAYS_ = 4;
    static public final int IN_THE_PAST_12_MONTHS__HAVE_YOU_HAD_INJECTIONS_FOR_EXPOSURE_TO_RABIES_OR_HAVE_YOU_RECEIVED_ANY_EXPERIMENTAL_VACCINE_ = 10;
    static public final int IN_THE_PAST_3_YEARS__HAVE_YOU_HAD_MALARIA_OR_SYMPTOMS_OF_MALARIA_ = 9;
    static public final int IN_THE_PAST_4_WEEKS__HAVE_YOU_HAD_ANY_VACCINATIONS_ = 11;
    static public final int IN_THE_PAST_SIX_MONTHS__HAVE_YOU_HAD_SURGERY_ = 3;
    static public final int IN_THE_PAST_SIX_MONTHS__HAVE_YOU_SUFFERED_FROM_HEART_RELATED_CHEST_PAIN_OR_HEART_DISEASE_ = 2;
}
