
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface EthnicityType
{
    static public final int AFRICAN_AMERICAN = 3;
    static public final int AMERICAN_INDIAN_ALASKAN_NATIVE = 1;
    static public final int ASIAN_PACIFIC_ISLANDER = 4;
    static public final int CAUCASIAN = 2;
    static public final int HISPANIC = 5;
    static public final int OTHER = 6;
    static public final int UNKNOWN = 0;
}
