
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface FieldChangeType
{
    static public final int ADDITION = 1;
    static public final int CREATION = 0;
    static public final int DELETION = 3;
    static public final int MODIFICATION = 2;
}
