
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface GenderType
{
    static public final int FEMALE = 1;
    static public final int MALE = 0;
    static public final int NOT_APPLICABLE = 2;
}
