
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface LanguageType
{
    static public final int CHINESE = 5;
    static public final int ENGLISH = 0;
    static public final int FRENCH = 2;
    static public final int GERMAN = 3;
    static public final int ITALIAN = 4;
    static public final int JAPANESE = 6;
    static public final int KOREAN = 7;
    static public final int OTHER = 9;
    static public final int SPANISH = 1;
    static public final int VIETNAMESE = 8;
}
