
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface MeasurementUnitType
{
    static public final int MILLIGRAMS = 1;
    static public final int MILLILITERS = 2;
    static public final int UNITS = 3;
    static public final int UNSPECIFIED = 0;
}
