
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface MonthOfYear
{
    static public final int APRIL = 3;
    static public final int AUGUST = 7;
    static public final int DECEMBER = 11;
    static public final int FEBRUARY = 1;
    static public final int JANUARY = 0;
    static public final int JULY = 6;
    static public final int JUNE = 5;
    static public final int MARCH = 2;
    static public final int MAY = 4;
    static public final int NOVEMBER = 10;
    static public final int OCTOBER = 9;
    static public final int SEPTEMBER = 8;
}
