
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface NamePrefixType
{
    static public final int MRS_ = 2;
    static public final int MR_ = 0;
    static public final int MS_ = 1;
}
