
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface OrgIndustryType
{
    static public final int AGRICULTURE = 0;
    static public final int APPAREL = 1;
    static public final int BANKING = 2;
    static public final int BIOTECHNOLOGY = 3;
    static public final int COMMUNICATIONS = 4;
    static public final int CONSTRUCTION = 5;
    static public final int CONSULTING = 6;
    static public final int EDUCATION = 7;
    static public final int ELECTRONICS = 8;
    static public final int ENERGY = 9;
    static public final int ENGINEERING = 10;
    static public final int ENTERTAINMENT = 11;
    static public final int ENVIRONMENTAL = 12;
    static public final int FINANCE = 13;
    static public final int FOOD_AND_BEVERAGE = 14;
    static public final int GOVERNMENT = 15;
    static public final int HEALTHCARE = 16;
    static public final int HOSPITALITY = 17;
    static public final int INSURANCE = 18;
    static public final int MACHINERY = 19;
    static public final int MANUFACTURING = 20;
    static public final int MEDIA = 21;
    static public final int NOT_FOR_PROFIT = 22;
    static public final int OTHER = 30;
    static public final int RECREATION = 23;
    static public final int RETAIL = 24;
    static public final int SHIPPING = 25;
    static public final int TECHNOLOGY = 26;
    static public final int TELECOMMUNICATIONS = 27;
    static public final int TRANSPORTATION = 28;
    static public final int UTILITIES = 29;
}
