
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface OrgIdentifierType
{
    static public final int BLUECROSS_BLUESHIELD_ID = 6;
    static public final int CLIA_ID = 7;
    static public final int EMPLOYER_ID = 1;
    static public final int INSURANCE_COMPANY_PROVIDER_ID = 8;
    static public final int MEDICAID_ID = 3;
    static public final int MEDICARE_ID = 4;
    static public final int OTHER_ID = 9;
    static public final int STATE_ID = 2;
    static public final int TAX_ID = 0;
    static public final int WORKERS_COMP_ID = 5;
}
