
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface OrgLevelType
{
    static public final int BRANCH = 1;
    static public final int COMPANY = 0;
    static public final int DEPARTMENT = 2;
}
