
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface OrgOwnershipType
{
    static public final int OTHER = 3;
    static public final int PRIVATE = 1;
    static public final int PUBLIC = 0;
    static public final int SUBSIDIARY = 2;
}
