
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface OrgRelationshipType
{
    static public final int ANCESTOR_OF_ORG = 1000;
    static public final int CHILD_OF_ORG = 1030;
    static public final int CLIENT = 1;
    static public final int DESCENDENT_OF_ORG = 1040;
    static public final int OUR_FIRM = 0;
    static public final int PARENT_OF_ORG = 1010;
    static public final int PARTNER_FIELD_NAME = 3;
    static public final int SIBLING_OF_ORG = 1020;
    static public final int VENDOR = 2;
}
