
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface OrgType
{
    static public final int ANCILLIARY_SERVICE = 11;
    static public final int CLINIC = 3;
    static public final int DIAGNOSTIC_SERVICES = 5;
    static public final int EMPLOYER = 9;
    static public final int FACILITY_SITE = 4;
    static public final int HOSPITAL = 6;
    static public final int INSURANCE = 8;
    static public final int IPA = 10;
    static public final int OTHER = 13;
    static public final int PHARMACY = 12;
    static public final int PRACTICE = 2;
    static public final int THERAPEUTIC_SERVICES = 7;
    static public final int TRIAL_SITE = 1;
    static public final int TRIAL_SPONSOR = 0;
}
