
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface OrgType
{
    static public final int ANCILLIARY_SERVICE = 9;
    static public final int CLINIC = 1;
    static public final int DIAGNOSTIC_SERVICES = 3;
    static public final int EMPLOYER = 7;
    static public final int FACILITY_SITE = 2;
    static public final int HOSPITAL = 4;
    static public final int INSURANCE = 6;
    static public final int IPA = 8;
    static public final int OTHER = 11;
    static public final int PHARMACY = 10;
    static public final int PRACTICE = 0;
    static public final int THERAPEUTIC_SERVICES = 5;
}
