
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface PersonStudyRelType
{
    static public final int COINVESTIGATOR = 4;
    static public final int COORDINATOR = 1;
    static public final int OTHER = 5;
    static public final int PHYSICIAN = 2;
    static public final int PRINCIPAL_INVESTIGATOR = 3;
    static public final int SUBJECT = 0;
}
