
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface PersonRoleType
{
    static public final int FUNCTIONAL_ROLE__USED_FOR_BUSINESS_RULES_PROCESSING_ = 1;
    static public final int SECURITY_ROLE__USED_FOR_AUTHORIZATION_ = 0;
}
