
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface PersonIndicationType
{
    static public final int ADVANCE_DIRECTIVE__PATIENT_ = 4;
    static public final int ADVANCE_DIRECTIVE__PHYSICIAN_ = 5;
    static public final int ENVIRONMENTAL_ALLERGY = 2;
    static public final int MEDICATION_ALLERGY = 1;
    static public final int MEDICATION_INTOLERANCE = 3;
    static public final int PREVENTIVE_CARE_PROTOCOL = 0;
}
