
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface PersonType
{
    static public final int LVN_LPN = 5;
    static public final int OTHER = 9;
    static public final int OTHER_CLINICAL_SERVICE_PROVIDER__ALTERNATE_BILLING_ = 4;
    static public final int OTHER_CLINICAL_SERVICE_PROVIDER__DIRECT_BILLING_ = 3;
    static public final int OTHER_NURSE = 7;
    static public final int PATIENT = 0;
    static public final int PHYSICIAN = 1;
    static public final int PHYSICIAN_EXTENDER__DIRECT_BILLING_ = 2;
    static public final int RN = 6;
    static public final int STAFF = 8;
}
