
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface PersonRelationshipType
{
    static public final int BROTHER = 10;
    static public final int CADAVER_DONOR = 15;
    static public final int CARE_PROVIDER = 25;
    static public final int COUSIN = 23;
    static public final int EMERGENCY_CONTACT = 24;
    static public final int EMPLOYEE = 11;
    static public final int FATHER = 3;
    static public final int FOSTER_CHILD = 7;
    static public final int GRANDCHILD = 16;
    static public final int GRANDPARENT = 22;
    static public final int HANDICAPPED_DEPENDENT = 13;
    static public final int INJURED_PLAINTIFF = 18;
    static public final int MINOR_DEPENDENT_OF_A_MINOR_DEPENDENT = 20;
    static public final int MOTHER = 2;
    static public final int NATURAL_ADOPTED_CHILD__INSURED_DOES_NOT_HAVE_FINANCIAL_RESP__ = 5;
    static public final int NATURAL_ADOPTED_CHILD__INSURED_HAS_FINANCIAL_RESPONSIBILITY_ = 4;
    static public final int NIECE_NEPHEW = 17;
    static public final int ORGAN_DONOR = 14;
    static public final int OTHER = 26;
    static public final int PARENT = 21;
    static public final int SELF = 0;
    static public final int SISTER = 9;
    static public final int SPONSORED_DEPENDENT = 19;
    static public final int SPOUSE = 1;
    static public final int STEP_CHILD = 6;
    static public final int UNKNOWN_OTHER = 12;
    static public final int WARD_OF_THE_COURT = 8;
}
