
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface PersonOrgRelType
{
    static public final int ADMINISTRATOR = 5;
    static public final int EMPLOYEE = 0;
    static public final int OTHER = 9;
    static public final int OTHER_NURSE = 7;
    static public final int PATIENT = 3;
    static public final int PHYSICIAN = 4;
    static public final int REGISTERED_NURSE = 6;
    static public final int RETIRED = 1;
    static public final int STAFF = 8;
    static public final int STUDENT = 2;
}
