
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface PersonNoteType
{
    static public final int MEDICAL = 1;
    static public final int NON_MEDICAL = 2;
    static public final int UNKNOWN = 0;
}
