
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface PersonLicenseType
{
    static public final int BCBS = 4;
    static public final int BOARD_CERTIFICATION = 3;
    static public final int CHAMPUS = 13;
    static public final int DEA = 0;
    static public final int DPS = 1;
    static public final int EPSDT = 7;
    static public final int IRS = 2;
    static public final int MEDICAID = 9;
    static public final int MEDICARE = 8;
    static public final int MEMORIAL_SISTERS_CHARITY = 6;
    static public final int NATIONAL_PROVIDER_ID = 14;
    static public final int NURSING_LICENSE = 5;
    static public final int OTHER = 15;
    static public final int RAILROAD_MEDICARE = 12;
    static public final int TAX_ID = 11;
    static public final int UPIN = 10;
}
