
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface RecordState
{
    static public final int CURRENT = 1;
    static public final int PAST = 0;
}
