
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface SessionStatusType
{
    static public final int ACTIVE = 0;
    static public final int INACTIVE__SYSTEM_FORCED_LOGOUT_ = 3;
    static public final int INACTIVE__TIMEOUT_ = 4;
    static public final int INACTIVE__USER_FORCED_LOGOUT_ = 2;
    static public final int INACTIVE__USER_NORMAL_LOGOUT_ = 1;
}
