
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface StudyOrgRelStatus
{
    static public final int ACTIVE = 1;
    static public final int INACTIVE = 0;
    static public final int UNKNOWN = 99;
}
