
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface StudyStageType
{
    static public final int PHASE_I = 0;
    static public final int PHASE_II = 1;
    static public final int PHASE_III = 2;
}
