
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface StudyOrgRelationType
{
    static public final int ADMINISTRATOR = 0;
    static public final int OTHER = 5;
    static public final int PARTICIPANT = 2;
    static public final int SITE = 3;
    static public final int SPONSOR = 1;
    static public final int SUBJECT_SUPPLIER = 4;
}
