
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface StudyPersonRelationType
{
    static public final int ADMINISTRATOR = 2;
    static public final int COINVESTIGATOR = 5;
    static public final int OTHER = 6;
    static public final int PHYSICIAN = 3;
    static public final int PRINCIPAL_INVESTIGATOR = 4;
    static public final int SUBJECT = 0;
    static public final int SUBJECT__PLACEBO_ = 1;
}
