
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface StudyType
{
    static public final int DIAGNOSTIC = 2;
    static public final int PREVENTION = 1;
    static public final int SCREENING = 3;
    static public final int SUPPORTIVE_CARE = 4;
    static public final int TREATMENT = 0;
}
