
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface StudyStatus
{
    static public final int ACTIVE = 1;
    static public final int COMPLETE = 105;
    static public final int INACTIVE = 0;
    static public final int IN_PLANNING = 102;
    static public final int IN_PROGRESS = 103;
    static public final int NOT_DEFINED = 100;
    static public final int ON_HOLD = 104;
    static public final int PROPOSED = 101;
    static public final int UNKNOWN = 99;
}
