
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface StudyDurationType
{
    static public final int FIVE_MONTHS = 4;
    static public final int FOUR_MONTHS = 3;
    static public final int ONE_MONTH = 0;
    static public final int ONE_YEAR = 6;
    static public final int SIX_MONTHS = 5;
    static public final int THREE_MONTHS = 2;
    static public final int THREE_YEARS = 8;
    static public final int TWO_MONTHS = 1;
    static public final int TWO_YEARS = 7;
}
