
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface TableActivityType
{
    static public final int ADD = 1;
    static public final int DELETE = 3;
    static public final int OTHER = 4;
    static public final int UNKNOWN = 0;
    static public final int UPDATE = 2;
}
