
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.enum;

public interface USStateType
{
    static public final int ALABAMA = 0;
    static public final int ALASKA = 1;
    static public final int AMERICAN_SAMOA = 51;
    static public final int ARIZONA = 2;
    static public final int ARKANSAS = 3;
    static public final int CALIFORNIA = 4;
    static public final int COLORADO = 5;
    static public final int CONNECTICUT = 6;
    static public final int DELAWARE = 7;
    static public final int DISTRICT_OF_COLUMBIA = 8;
    static public final int FEDERATED_STATES_OF_MICRONESIA = 52;
    static public final int FLORIDA = 9;
    static public final int GEORGIA = 10;
    static public final int GUAM = 53;
    static public final int HAWAII = 11;
    static public final int IDAHO = 12;
    static public final int ILLINOIS = 13;
    static public final int INDIANA = 14;
    static public final int IOWA = 15;
    static public final int KANSAS = 16;
    static public final int KENTUCKY = 17;
    static public final int LOUISIANA = 18;
    static public final int MAINE = 19;
    static public final int MARSHALL_ISLANDS = 54;
    static public final int MARYLAND = 20;
    static public final int MASSACUSETTS = 21;
    static public final int MICHIGAN = 22;
    static public final int MINNESOTA = 23;
    static public final int MISSISSIPPI = 24;
    static public final int MISSOURI = 25;
    static public final int MONTANA = 26;
    static public final int NEBRASKA = 27;
    static public final int NEVADA = 28;
    static public final int NEW_HAMPSHIRE = 29;
    static public final int NEW_JERSEY = 30;
    static public final int NEW_MEXICO = 31;
    static public final int NEW_YORK = 32;
    static public final int NORTHERN_MARIANA_ISLANDS = 55;
    static public final int NORTH_CAROLINA = 33;
    static public final int NORTH_DAKOTA = 34;
    static public final int OHIO = 35;
    static public final int OKLAHOMA = 36;
    static public final int OREGON = 37;
    static public final int OTHER = 59;
    static public final int PALAU = 56;
    static public final int PENNSYLVANIA = 38;
    static public final int PUERTO_RICO = 57;
    static public final int RHODE_ISLAND = 39;
    static public final int SOUTH_CAROLINA = 40;
    static public final int SOUTH_DAKOTA = 41;
    static public final int TENNESSEE = 42;
    static public final int TEXAS = 43;
    static public final int UTAH = 44;
    static public final int VERMONT = 45;
    static public final int VIRGINIA = 46;
    static public final int VIRGIN_ISLANDS = 58;
    static public final int WASHINGTON = 47;
    static public final int WEST_VIRGINIA = 48;
    static public final int WISCONSIN = 49;
    static public final int WYOMING = 50;
}
