
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.query.db;

public interface Respondent
{
    static public final String ALL = "db.Respondent.all";
    static public final String LOCK = "db.Respondent.lock";
    static public final String LOOKUP = "db.Respondent.lookup";
    static public final String SUMMARY = "db.Respondent.summary";
}
