
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.query.db;

public interface RiskResponse
{
    static public final String ALL_RESPONSES_FOR_PARTICULAR_PIN = "db.Risk_Response.all-responses-for-particular-pin";
}
