
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.query.db;

public interface VisitedPage
{
    static public final String LOOKUP_BY_PIN = "db.Visited_Page.lookup-by-pin";
}
