
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface CurrentEnvironment
{
    static public final String APPROACH = "approach";
    static public final String APPROACH_EXPL = "approach_expl";
    static public final String PIN = "pin";
    static public final String RISKS_DELTA = "risks_delta";
    static public final String RISKS_DELTA_EXPL = "risks_delta_expl";
    static public final String RISKS_DEPT = "risks_dept";
    static public final String RISKS_DEPT_EXPL = "risks_dept_expl";
    static public final String RISKS_DIV = "risks_div";
    static public final String RISKS_DIV_EXPL = "risks_div_expl";
    static public final String RISKS_PRJ = "risks_prj";
    static public final String RISKS_PRJ_EXPL = "risks_prj_expl";
}
