
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface Respondent
{
    static public final String BUSINESS_UNIT = "business_unit";
    static public final String DIVISION = "division";
    static public final String FUNCTION = "function";
    static public final String LOCATION = "location";
    static public final String LOCKED = "locked";
    static public final String PIN = "pin";
    static public final String TITLE = "title";
    static public final String YRS_CURRENT_POS = "yrs_current_pos";
    static public final String YRS_FIRM = "yrs_firm";
}
