
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Org
{
    static public final int BUSINESS_END_TIME = 9;
    static public final int BUSINESS_START_TIME = 8;
    static public final int CR_SESS_ID = 1;
    static public final int CR_STAMP = 0;
    static public final int EMPLOYEES = 7;
    static public final int ORG_ABBREV = 6;
    static public final int ORG_CODE = 4;
    static public final int ORG_ID = 3;
    static public final int ORG_NAME = 5;
    static public final int REC_STAT_ID = 2;
    static public final int TIME_ZONE = 10;
}
