
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface OrgContact
{
    static public final int CR_SESS_ID = 1;
    static public final int CR_STAMP = 0;
    static public final int METHOD_NAME = 6;
    static public final int METHOD_TYPE = 5;
    static public final int METHOD_VALUE = 7;
    static public final int PARENT_ID = 4;
    static public final int PHONE_AC = 9;
    static public final int PHONE_CC = 8;
    static public final int PHONE_PREFIX = 10;
    static public final int PHONE_SUFFIX = 11;
    static public final int REC_STAT_ID = 2;
    static public final int SYSTEM_ID = 3;
}
