
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface OrgPersonIdSrcType
{
    static public final int ABBREV = 7;
    static public final int CAPTION = 6;
    static public final int CR_SESS_ID = 1;
    static public final int CR_STAMP = 0;
    static public final int ITEM_ID = 5;
    static public final int ORG_ID = 4;
    static public final int REC_STAT_ID = 2;
    static public final int SYSTEM_ID = 3;
}
