
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface OrgRelationship
{
    static public final int CR_SESS_ID = 1;
    static public final int CR_STAMP = 0;
    static public final int PARENT_ID = 4;
    static public final int REC_STAT_ID = 2;
    static public final int REL_BEGIN = 8;
    static public final int REL_DESCR = 10;
    static public final int REL_END = 9;
    static public final int REL_ENTITY_ID = 5;
    static public final int REL_TYPE = 7;
    static public final int REL_TYPE_ID = 6;
    static public final int SYSTEM_ID = 3;
}
