
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface PerLanguageIdSet
{
    static public final int ENUM_INDEX = 2;
    static public final int ENUM_VALUE = 3;
    static public final int PARENT_ID = 1;
    static public final int SYSTEM_ID = 0;
}
