
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface PersonLogin
{
    static public final int CR_SESS_ID = 1;
    static public final int CR_STAMP = 0;
    static public final int LOGIN_STATUS = 7;
    static public final int PASSWORD = 6;
    static public final int PERSON_ID = 4;
    static public final int QUANTITY = 8;
    static public final int REC_STAT_ID = 2;
    static public final int SYSTEM_ID = 3;
    static public final int USER_ID = 5;
}
