
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface PersonSessionActivity
{
    static public final int ACTION_KEY = 5;
    static public final int ACTION_SCOPE = 4;
    static public final int ACTION_TYPE = 3;
    static public final int ACTIVITY_DATA = 7;
    static public final int ACTIVITY_STAMP = 2;
    static public final int ACTIVITY_TYPE = 1;
    static public final int DETAIL_LEVEL = 6;
    static public final int SESSION_ID = 0;
}
