
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Person
{
    static public final int AGE = 22;
    static public final int BIRTH_DATE = 21;
    static public final int BLOOD_TYPE_ID = 20;
    static public final int COMPLETE_NAME = 12;
    static public final int COMPLETE_SORTABLE_NAME = 14;
    static public final int CR_SESS_ID = 1;
    static public final int CR_STAMP = 0;
    static public final int ETHNICITY_ID = 17;
    static public final int GENDER_ID = 16;
    static public final int LANGUAGE_ID = 18;
    static public final int MARITAL_STATUS_ID = 19;
    static public final int NAME_FIRST = 6;
    static public final int NAME_LAST = 8;
    static public final int NAME_MIDDLE = 7;
    static public final int NAME_PREFIX = 5;
    static public final int NAME_PREFIX_ID = 4;
    static public final int NAME_SUFFIX = 9;
    static public final int PERSON_ID = 3;
    static public final int REC_STAT_ID = 2;
    static public final int SHORT_NAME = 10;
    static public final int SHORT_SORTABLE_NAME = 13;
    static public final int SIMPLE_NAME = 11;
    static public final int SSN = 15;
}
