
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface PersonSessionViewCount
{
    static public final int SESSION_ID = 0;
    static public final int VIEW_ARL = 7;
    static public final int VIEW_CAPTION = 6;
    static public final int VIEW_COUNT = 5;
    static public final int VIEW_INIT = 1;
    static public final int VIEW_KEY = 4;
    static public final int VIEW_LATEST = 2;
    static public final int VIEW_SCOPE = 3;
}
