
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface PersonAddress
{
    static public final int ADDRESS_NAME = 5;
    static public final int ADDRESS_TYPE_ID = 7;
    static public final int CITY = 10;
    static public final int COUNTRY = 15;
    static public final int COUNTY = 11;
    static public final int CR_SESS_ID = 1;
    static public final int CR_STAMP = 0;
    static public final int LINE1 = 8;
    static public final int LINE2 = 9;
    static public final int MAILING = 6;
    static public final int PARENT_ID = 4;
    static public final int REC_STAT_ID = 2;
    static public final int STATE = 13;
    static public final int STATE_ID = 12;
    static public final int SYSTEM_ID = 3;
    static public final int ZIP = 14;
}
