
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface PersonSession
{
    static public final int FIRST_ACCESS = 5;
    static public final int LAST_ACCESS = 6;
    static public final int ORG_ID = 2;
    static public final int PERSON_ID = 1;
    static public final int REMOTE_ADDR = 4;
    static public final int REMOTE_HOST = 3;
    static public final int SESSION_ID = 0;
}
