
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface StaffLicense
{
    static public final int CR_SESS_ID = 1;
    static public final int CR_STAMP = 0;
    static public final int EXPIRATION_DATE = 9;
    static public final int LICENSE_NUM = 8;
    static public final int LICENSE_STATE = 11;
    static public final int LICENSE_STATE_ID = 10;
    static public final int LICENSE_TYPE = 7;
    static public final int LICENSE_TYPE_ID = 6;
    static public final int ORG_ID = 5;
    static public final int PERSON_ID = 4;
    static public final int REC_STAT_ID = 2;
    static public final int SPECIALITY_TYPE_ID = 12;
    static public final int SYSTEM_ID = 3;
}
