
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.sql.schema.db.table;

public interface Study
{
    static public final int ACTUAL_END_DATE = 11;
    static public final int CR_SESS_ID = 1;
    static public final int CR_STAMP = 0;
    static public final int IRB_APPROVAL_DATE = 14;
    static public final int IRB_EXPIRATION_DATE = 15;
    static public final int IRB_NAME = 12;
    static public final int IRB_NUMBER = 13;
    static public final int REC_STAT_ID = 2;
    static public final int START_DATE = 9;
    static public final int STUDY_CODE = 4;
    static public final int STUDY_DESCR = 6;
    static public final int STUDY_ID = 3;
    static public final int STUDY_NAME = 5;
    static public final int STUDY_STAGE = 8;
    static public final int STUDY_STATUS = 7;
    static public final int TARGET_END_DATE = 10;
}
