
/* this file is generated by com.netspective.sparx.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package auto.dcb.subject;

import com.netspective.sparx.form.*;
import com.netspective.sparx.form.field.*;
import com.netspective.sparx.form.field.type.*;

public class JournalContext
{
    public static final String DIALOG_ID = "subject.journal";
    private DialogContext dialogContext;
    private DialogContext.DialogFieldStates fieldStates;

    public JournalContext(DialogContext dc)
    {
        this.dialogContext = dc;
        this.fieldStates = dc.getFieldStates();
    }

    public DialogContext getDialogContext() { return dialogContext; }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getPersonIdState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("person_id"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getPersonId() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getPersonIdState().getValue(); }
	public DialogFieldFlags getPersonIdStateFlags() { return getPersonIdState().getStateFlags(); }
	public String getPersonIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.person_id"); }
	public String getPersonIdPublicRequestParam() { return dialogContext.getRequest().getParameter("person_id"); }
	public com.netspective.sparx.form.field.type.TextField getPersonIdField() { return (com.netspective.sparx.form.field.type.TextField) getPersonIdState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getNameState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("name"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getName() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getNameState().getValue(); }
	public DialogFieldFlags getNameStateFlags() { return getNameState().getStateFlags(); }
	public String getNamePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.name"); }
	public String getNamePublicRequestParam() { return dialogContext.getRequest().getParameter("name"); }
	public com.netspective.sparx.form.field.type.TextField getNameField() { return (com.netspective.sparx.form.field.type.TextField) getNameState().getField(); }

	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState getDateState() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState) fieldStates.getState("date"); }
	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue getDate() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue) getDateState().getValue(); }
	public DialogFieldFlags getDateStateFlags() { return getDateState().getStateFlags(); }
	public String getDatePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.date"); }
	public String getDatePublicRequestParam() { return dialogContext.getRequest().getParameter("date"); }
	public com.netspective.sparx.form.field.type.DateTimeField getDateField() { return (com.netspective.sparx.form.field.type.DateTimeField) getDateState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getJournalState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("journal"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getJournal() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getJournalState().getValue(); }
	public DialogFieldFlags getJournalStateFlags() { return getJournalState().getStateFlags(); }
	public String getJournalPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.journal"); }
	public String getJournalPublicRequestParam() { return dialogContext.getRequest().getParameter("journal"); }
	public com.netspective.sparx.form.field.type.MemoField getJournalField() { return (com.netspective.sparx.form.field.type.MemoField) getJournalState().getField(); }

	public com.netspective.sparx.form.field.type.IntegerField.IntegerFieldState getNoteTypeIdState() { return (com.netspective.sparx.form.field.type.IntegerField.IntegerFieldState) fieldStates.getState("note_type_id"); }
	public com.netspective.sparx.form.field.type.IntegerField.IntegerFieldState.IntegerFieldValue getNoteTypeId() { return (com.netspective.sparx.form.field.type.IntegerField.IntegerFieldState.IntegerFieldValue) getNoteTypeIdState().getValue(); }
	public DialogFieldFlags getNoteTypeIdStateFlags() { return getNoteTypeIdState().getStateFlags(); }
	public String getNoteTypeIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.note_type_id"); }
	public String getNoteTypeIdPublicRequestParam() { return dialogContext.getRequest().getParameter("note_type_id"); }
	public com.netspective.sparx.form.field.type.IntegerField getNoteTypeIdField() { return (com.netspective.sparx.form.field.type.IntegerField) getNoteTypeIdState().getField(); }

}
