
/* this file is generated by com.netspective.sparx.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package auto.dcb.subject;

import com.netspective.sparx.form.*;
import com.netspective.sparx.form.field.*;
import com.netspective.sparx.form.field.type.*;

public class ProfileContext
{
    public static final String DIALOG_ID = "subject.profile";
    private DialogContext dialogContext;
    private DialogContext.DialogFieldStates fieldStates;

    public ProfileContext(DialogContext dc)
    {
        this.dialogContext = dc;
        this.fieldStates = dc.getFieldStates();
    }

    public DialogContext getDialogContext() { return dialogContext; }

	public com.netspective.sparx.form.field.type.IntegerField.IntegerFieldState getPersonIdState() { return (com.netspective.sparx.form.field.type.IntegerField.IntegerFieldState) fieldStates.getState("person_id"); }
	public com.netspective.sparx.form.field.type.IntegerField.IntegerFieldState.IntegerFieldValue getPersonId() { return (com.netspective.sparx.form.field.type.IntegerField.IntegerFieldState.IntegerFieldValue) getPersonIdState().getValue(); }
	public DialogFieldFlags getPersonIdStateFlags() { return getPersonIdState().getStateFlags(); }
	public String getPersonIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.person_id"); }
	public String getPersonIdPublicRequestParam() { return dialogContext.getRequest().getParameter("person_id"); }
	public com.netspective.sparx.form.field.type.IntegerField getPersonIdField() { return (com.netspective.sparx.form.field.type.IntegerField) getPersonIdState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getOrgIdState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("org_id"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getOrgId() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getOrgIdState().getValue(); }
	public DialogFieldFlags getOrgIdStateFlags() { return getOrgIdState().getStateFlags(); }
	public String getOrgIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.org_id"); }
	public String getOrgIdPublicRequestParam() { return dialogContext.getRequest().getParameter("org_id"); }
	public com.netspective.sparx.form.field.type.TextField getOrgIdField() { return (com.netspective.sparx.form.field.type.TextField) getOrgIdState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getStudyIdState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("study_id"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getStudyId() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getStudyIdState().getValue(); }
	public DialogFieldFlags getStudyIdStateFlags() { return getStudyIdState().getStateFlags(); }
	public String getStudyIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.study_id"); }
	public String getStudyIdPublicRequestParam() { return dialogContext.getRequest().getParameter("study_id"); }
	public com.netspective.sparx.form.field.type.TextField getStudyIdField() { return (com.netspective.sparx.form.field.type.TextField) getStudyIdState().getField(); }


	public com.netspective.sparx.form.field.DialogField.State getFullNameState() { return (com.netspective.sparx.form.field.DialogField.State) fieldStates.getState("fullName"); }
	public com.netspective.sparx.form.field.DialogField.State.BasicStateValue getFullName() { return (com.netspective.sparx.form.field.DialogField.State.BasicStateValue) getFullNameState().getValue(); }
	public DialogFieldFlags getFullNameStateFlags() { return getFullNameState().getStateFlags(); }
	public String getFullNamePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.fullName"); }
	public String getFullNamePublicRequestParam() { return dialogContext.getRequest().getParameter("fullName"); }
	public com.netspective.sparx.form.field.DialogField getFullNameField() { return (com.netspective.sparx.form.field.DialogField) getFullNameState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getFullName_namePrefixState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("fullName.name_prefix"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getFullName_namePrefix() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getFullName_namePrefixState().getValue(); }
	public DialogFieldFlags getFullName_namePrefixStateFlags() { return getFullName_namePrefixState().getStateFlags(); }
	public String getFullName_namePrefixPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.fullName.name_prefix"); }
	public String getFullName_namePrefixPublicRequestParam() { return dialogContext.getRequest().getParameter("fullName.name_prefix"); }
	public com.netspective.sparx.form.field.type.SelectField getFullName_namePrefixField() { return (com.netspective.sparx.form.field.type.SelectField) getFullName_namePrefixState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getFullName_nameLastState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("fullName.name_last"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getFullName_nameLast() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getFullName_nameLastState().getValue(); }
	public DialogFieldFlags getFullName_nameLastStateFlags() { return getFullName_nameLastState().getStateFlags(); }
	public String getFullName_nameLastPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.fullName.name_last"); }
	public String getFullName_nameLastPublicRequestParam() { return dialogContext.getRequest().getParameter("fullName.name_last"); }
	public com.netspective.sparx.form.field.type.TextField getFullName_nameLastField() { return (com.netspective.sparx.form.field.type.TextField) getFullName_nameLastState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getFullName_nameFirstState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("fullName.name_first"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getFullName_nameFirst() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getFullName_nameFirstState().getValue(); }
	public DialogFieldFlags getFullName_nameFirstStateFlags() { return getFullName_nameFirstState().getStateFlags(); }
	public String getFullName_nameFirstPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.fullName.name_first"); }
	public String getFullName_nameFirstPublicRequestParam() { return dialogContext.getRequest().getParameter("fullName.name_first"); }
	public com.netspective.sparx.form.field.type.TextField getFullName_nameFirstField() { return (com.netspective.sparx.form.field.type.TextField) getFullName_nameFirstState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getFullName_nameMiddleState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("fullName.name_middle"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getFullName_nameMiddle() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getFullName_nameMiddleState().getValue(); }
	public DialogFieldFlags getFullName_nameMiddleStateFlags() { return getFullName_nameMiddleState().getStateFlags(); }
	public String getFullName_nameMiddlePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.fullName.name_middle"); }
	public String getFullName_nameMiddlePublicRequestParam() { return dialogContext.getRequest().getParameter("fullName.name_middle"); }
	public com.netspective.sparx.form.field.type.TextField getFullName_nameMiddleField() { return (com.netspective.sparx.form.field.type.TextField) getFullName_nameMiddleState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getFullName_nameSuffixState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("fullName.name_suffix"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getFullName_nameSuffix() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getFullName_nameSuffixState().getValue(); }
	public DialogFieldFlags getFullName_nameSuffixStateFlags() { return getFullName_nameSuffixState().getStateFlags(); }
	public String getFullName_nameSuffixPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.fullName.name_suffix"); }
	public String getFullName_nameSuffixPublicRequestParam() { return dialogContext.getRequest().getParameter("fullName.name_suffix"); }
	public com.netspective.sparx.form.field.type.TextField getFullName_nameSuffixField() { return (com.netspective.sparx.form.field.type.TextField) getFullName_nameSuffixState().getField(); }


	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState getDateOfBirthState() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState) fieldStates.getState("date_of_birth"); }
	public com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue getDateOfBirth() { return (com.netspective.sparx.form.field.type.DateTimeField.DateTimeFieldState.DateTimeFieldValue) getDateOfBirthState().getValue(); }
	public DialogFieldFlags getDateOfBirthStateFlags() { return getDateOfBirthState().getStateFlags(); }
	public String getDateOfBirthPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.date_of_birth"); }
	public String getDateOfBirthPublicRequestParam() { return dialogContext.getRequest().getParameter("date_of_birth"); }
	public com.netspective.sparx.form.field.type.DateTimeField getDateOfBirthField() { return (com.netspective.sparx.form.field.type.DateTimeField) getDateOfBirthState().getField(); }

	public com.netspective.sparx.form.field.type.SocialSecurityField.State getSsnState() { return (com.netspective.sparx.form.field.type.SocialSecurityField.State) fieldStates.getState("ssn"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getSsn() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getSsnState().getValue(); }
	public DialogFieldFlags getSsnStateFlags() { return getSsnState().getStateFlags(); }
	public String getSsnPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.ssn"); }
	public String getSsnPublicRequestParam() { return dialogContext.getRequest().getParameter("ssn"); }
	public com.netspective.sparx.form.field.type.SocialSecurityField getSsnField() { return (com.netspective.sparx.form.field.type.SocialSecurityField) getSsnState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getGenderIdState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("gender_id"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getGenderId() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getGenderIdState().getValue(); }
	public DialogFieldFlags getGenderIdStateFlags() { return getGenderIdState().getStateFlags(); }
	public String getGenderIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.gender_id"); }
	public String getGenderIdPublicRequestParam() { return dialogContext.getRequest().getParameter("gender_id"); }
	public com.netspective.sparx.form.field.type.SelectField getGenderIdField() { return (com.netspective.sparx.form.field.type.SelectField) getGenderIdState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getMaritalStatusIdState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("marital_status_id"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getMaritalStatusId() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getMaritalStatusIdState().getValue(); }
	public DialogFieldFlags getMaritalStatusIdStateFlags() { return getMaritalStatusIdState().getStateFlags(); }
	public String getMaritalStatusIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.marital_status_id"); }
	public String getMaritalStatusIdPublicRequestParam() { return dialogContext.getRequest().getParameter("marital_status_id"); }
	public com.netspective.sparx.form.field.type.SelectField getMaritalStatusIdField() { return (com.netspective.sparx.form.field.type.SelectField) getMaritalStatusIdState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getBloodTypeIdState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("blood_type_id"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getBloodTypeId() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getBloodTypeIdState().getValue(); }
	public DialogFieldFlags getBloodTypeIdStateFlags() { return getBloodTypeIdState().getStateFlags(); }
	public String getBloodTypeIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.blood_type_id"); }
	public String getBloodTypeIdPublicRequestParam() { return dialogContext.getRequest().getParameter("blood_type_id"); }
	public com.netspective.sparx.form.field.type.SelectField getBloodTypeIdField() { return (com.netspective.sparx.form.field.type.SelectField) getBloodTypeIdState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getEthnicityIdState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("ethnicity_id"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getEthnicityId() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getEthnicityIdState().getValue(); }
	public DialogFieldFlags getEthnicityIdStateFlags() { return getEthnicityIdState().getStateFlags(); }
	public String getEthnicityIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.ethnicity_id"); }
	public String getEthnicityIdPublicRequestParam() { return dialogContext.getRequest().getParameter("ethnicity_id"); }
	public com.netspective.sparx.form.field.type.SelectField getEthnicityIdField() { return (com.netspective.sparx.form.field.type.SelectField) getEthnicityIdState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getLanguageIdState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("language_id"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getLanguageId() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getLanguageIdState().getValue(); }
	public DialogFieldFlags getLanguageIdStateFlags() { return getLanguageIdState().getStateFlags(); }
	public String getLanguageIdPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.language_id"); }
	public String getLanguageIdPublicRequestParam() { return dialogContext.getRequest().getParameter("language_id"); }
	public com.netspective.sparx.form.field.type.SelectField getLanguageIdField() { return (com.netspective.sparx.form.field.type.SelectField) getLanguageIdState().getField(); }


	public com.netspective.sparx.form.field.type.TextField.TextFieldState getLine1State() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("line1"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getLine1() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getLine1State().getValue(); }
	public DialogFieldFlags getLine1StateFlags() { return getLine1State().getStateFlags(); }
	public String getLine1PrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.line1"); }
	public String getLine1PublicRequestParam() { return dialogContext.getRequest().getParameter("line1"); }
	public com.netspective.sparx.form.field.type.TextField getLine1Field() { return (com.netspective.sparx.form.field.type.TextField) getLine1State().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getLine2State() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("line2"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getLine2() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getLine2State().getValue(); }
	public DialogFieldFlags getLine2StateFlags() { return getLine2State().getStateFlags(); }
	public String getLine2PrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.line2"); }
	public String getLine2PublicRequestParam() { return dialogContext.getRequest().getParameter("line2"); }
	public com.netspective.sparx.form.field.type.TextField getLine2Field() { return (com.netspective.sparx.form.field.type.TextField) getLine2State().getField(); }

	public com.netspective.sparx.form.field.DialogField.State getCityStateZipState() { return (com.netspective.sparx.form.field.DialogField.State) fieldStates.getState("cityStateZip"); }
	public com.netspective.sparx.form.field.DialogField.State.BasicStateValue getCityStateZip() { return (com.netspective.sparx.form.field.DialogField.State.BasicStateValue) getCityStateZipState().getValue(); }
	public DialogFieldFlags getCityStateZipStateFlags() { return getCityStateZipState().getStateFlags(); }
	public String getCityStateZipPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.cityStateZip"); }
	public String getCityStateZipPublicRequestParam() { return dialogContext.getRequest().getParameter("cityStateZip"); }
	public com.netspective.sparx.form.field.DialogField getCityStateZipField() { return (com.netspective.sparx.form.field.DialogField) getCityStateZipState().getField(); }

	public com.netspective.sparx.form.field.type.TextField.TextFieldState getCityStateZip_cityState() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState) fieldStates.getState("cityStateZip.city"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getCityStateZip_city() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getCityStateZip_cityState().getValue(); }
	public DialogFieldFlags getCityStateZip_cityStateFlags() { return getCityStateZip_cityState().getStateFlags(); }
	public String getCityStateZip_cityPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.cityStateZip.city"); }
	public String getCityStateZip_cityPublicRequestParam() { return dialogContext.getRequest().getParameter("cityStateZip.city"); }
	public com.netspective.sparx.form.field.type.TextField getCityStateZip_cityField() { return (com.netspective.sparx.form.field.type.TextField) getCityStateZip_cityState().getField(); }

	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState getCityStateZip_stateState() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState) fieldStates.getState("cityStateZip.state"); }
	public com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue getCityStateZip_state() { return (com.netspective.sparx.form.field.type.SelectField.SelectFieldState.SelectFieldValue) getCityStateZip_stateState().getValue(); }
	public DialogFieldFlags getCityStateZip_stateStateFlags() { return getCityStateZip_stateState().getStateFlags(); }
	public String getCityStateZip_statePrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.cityStateZip.state"); }
	public String getCityStateZip_statePublicRequestParam() { return dialogContext.getRequest().getParameter("cityStateZip.state"); }
	public com.netspective.sparx.form.field.type.SelectField getCityStateZip_stateField() { return (com.netspective.sparx.form.field.type.SelectField) getCityStateZip_stateState().getField(); }

	public com.netspective.sparx.form.field.type.ZipCodeField.ZipCodeFieldState getCityStateZip_zipState() { return (com.netspective.sparx.form.field.type.ZipCodeField.ZipCodeFieldState) fieldStates.getState("cityStateZip.zip"); }
	public com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue getCityStateZip_zip() { return (com.netspective.sparx.form.field.type.TextField.TextFieldState.TextFieldValue) getCityStateZip_zipState().getValue(); }
	public DialogFieldFlags getCityStateZip_zipStateFlags() { return getCityStateZip_zipState().getStateFlags(); }
	public String getCityStateZip_zipPrivateRequestParam() { return dialogContext.getRequest().getParameter("_dc.cityStateZip.zip"); }
	public String getCityStateZip_zipPublicRequestParam() { return dialogContext.getRequest().getParameter("cityStateZip.zip"); }
	public com.netspective.sparx.form.field.type.ZipCodeField getCityStateZip_zipField() { return (com.netspective.sparx.form.field.type.ZipCodeField) getCityStateZip_zipState().getField(); }

}
