
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form;

public interface Survey
{
    static public final String ADDITIONAL = "survey.additional";
    static public final String EXTERNAL = "survey.external";
    static public final String INTERNAL_FINANCIAL = "survey.internal_financial";
    static public final String INTERNAL_OPERATIONAL_BUSINESS_REPORTING = "survey.internal_operational_business_reporting";
    static public final String INTERNAL_OPERATIONAL_HUMAN_CAPITAL = "survey.internal_operational_human_capital";
    static public final String INTERNAL_OPERATIONAL_INTEGRITY = "survey.internal_operational_integrity";
    static public final String INTERNAL_OPERATIONAL_PROCESS = "survey.internal_operational_process";
    static public final String INTERNAL_OPERATIONAL_TECHNOLOGY = "survey.internal_operational_technology";
    static public final String INTERNAL_STRATEGIC = "survey.internal_strategic";
}
