
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface Account
{
    static public final String ACCOUNT_ID = "account_id";
    static public final String ADDR1 = "addr1";
    static public final String ADDR2 = "addr2";
    static public final String CITY = "city";
    static public final String COUNTRY = "country";
    static public final String EMAIL = "email";
    static public final String FIRST_NAME = "first_name";
    static public final String LAST_NAME = "last_name";
    static public final String PASSWORD = "password";
    static public final String PHONE = "phone";
    static public final String STATE = "state";
    static public final String STATUS = "status";
}
