
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface BannerData
{
    static public final String BANNER_DATA_ID = "banner_data_id";
    static public final String BANNER_NAME = "banner_name";
}
