
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface Item
{
    static public final String ATTR1 = "attr1";
    static public final String ATTR2 = "attr2";
    static public final String ATTR3 = "attr3";
    static public final String DESCR = "descr";
    static public final String IMAGE = "image";
    static public final String ITEM_ID = "item_id";
    static public final String NAME = "name";
    static public final String STATUS = "status";
}
