
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface LineItem
{
    static public final String ITEMNUM = "itemnum";
    static public final String LINEITEM_ID = "lineitem_id";
    static public final String QUANTITY = "quantity";
}
