
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface Orders
{
    static public final String BILL_ADDR1 = "bill_addr1";
    static public final String BILL_ADDR2 = "bill_addr2";
    static public final String BILL_CITY = "bill_city";
    static public final String BILL_COUNTRY = "bill_country";
    static public final String BILL_PHONE = "bill_phone";
    static public final String BILL_STATE = "bill_state";
    static public final String ORDER_DATE = "order_date";
    static public final String ORDERS_ID = "orders_id";
    static public final String SHIP_ADDR1 = "ship_addr1";
    static public final String SHIP_ADDR2 = "ship_addr2";
    static public final String SHIP_CITY = "ship_city";
    static public final String SHIP_COUNTRY = "ship_country";
    static public final String SHIP_PHONE = "ship_phone";
    static public final String SHIP_STATE = "ship_state";
}
