
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface OrderStatus
{
    static public final String ITEMNUM = "itemnum";
    static public final String ORDERSTATUS_ID = "orderstatus_id";
    static public final String STATUS = "status";
    static public final String TS = "ts";
}
