
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface Product
{
    static public final String DESCR = "descr";
    static public final String NAME = "name";
    static public final String PRODUCT_ID = "product_id";
}
