
/* this file is generated by com.netspective.commons.xdm.XdmIdentifierConstantsGenerator, do not modify (you can extend it, though) */

package auto.id.pres.form.schema.db;

public interface Supplier
{
    static public final String ADDR1 = "addr1";
    static public final String ADDR2 = "addr2";
    static public final String CITY = "city";
    static public final String COUNTRY = "country";
    static public final String NAME = "name";
    static public final String PHONE = "phone";
    static public final String STATE = "state";
    static public final String STATUS = "status";
    static public final String SUPPLIER_ID = "supplier_id";
}
